/**
 * 核查命令库种子数据
 * 涵盖网络设备、安全设备、服务器、数据库、中间件等类型
 * 包含各品牌、各系统的准确核查命令
 */

export interface SeedCommand {
  id: string;
  name: string;
  target: string;
  command: string;
  description: string;
  os: string;
  brand: string;
  deviceType: string;
  category: string;
  subCategory: string;
  createdAt?: string;
  updatedAt?: string;
}

export function getCommandSeeds(): SeedCommand[] {
  const now = new Date().toISOString();
  const commands: SeedCommand[] = [];

  // ========================
  // 一、网络设备 - 交换机
  // ========================

  // 1.1 华为交换机 (VRP系统)
  const huaweiSwitchCmds: SeedCommand[] = [
    {
      id: 'cmd-hsw-user-list',
      name: '查看用户列表',
      target: '华为交换机',
      command: 'display local-user',
      description: '查看所有本地用户账号信息',
      os: 'VRP',
      brand: '华为',
      deviceType: '交换机',
      category: '身份鉴别',
      subCategory: '用户管理',
    },
    {
      id: 'cmd-hsw-password-policy',
      name: '查看密码策略',
      target: '华为交换机',
      command: 'display password policy',
      description: '查看系统密码复杂度策略配置',
      os: 'VRP',
      brand: '华为',
      deviceType: '交换机',
      category: '身份鉴别',
      subCategory: '密码策略',
    },
    {
      id: 'cmd-hsw-acl',
      name: '查看ACL配置',
      target: '华为交换机',
      command: 'display acl all',
      description: '查看所有访问控制列表配置',
      os: 'VRP',
      brand: '华为',
      deviceType: '交换机',
      category: '访问控制',
      subCategory: 'ACL',
    },
    {
      id: 'cmd-hsw-port-security',
      name: '查看端口安全',
      target: '华为交换机',
      command: 'display port-security interface',
      description: '查看端口安全配置信息',
      os: 'VRP',
      brand: '华为',
      deviceType: '交换机',
      category: '访问控制',
      subCategory: '端口安全',
    },
    {
      id: 'cmd-hsw-vlan',
      name: '查看VLAN配置',
      target: '华为交换机',
      command: 'display vlan',
      description: '查看所有VLAN配置信息',
      os: 'VRP',
      brand: '华为',
      deviceType: '交换机',
      category: '网络架构',
      subCategory: 'VLAN',
    },
    {
      id: 'cmd-hsw-stp',
      name: '查看生成树配置',
      target: '华为交换机',
      command: 'display stp',
      description: '查看生成树协议状态和配置',
      os: 'VRP',
      brand: '华为',
      deviceType: '交换机',
      category: '网络架构',
      subCategory: '生成树',
    },
    {
      id: 'cmd-hsw-log',
      name: '查看日志配置',
      target: '华为交换机',
      command: 'display info-center',
      description: '查看日志服务器和日志级别配置',
      os: 'VRP',
      brand: '华为',
      deviceType: '交换机',
      category: '安全审计',
      subCategory: '日志配置',
    },
    {
      id: 'cmd-hsw-ssh',
      name: '查看SSH配置',
      target: '华为交换机',
      command: 'display ssh server status',
      description: '查看SSH服务状态和配置',
      os: 'VRP',
      brand: '华为',
      deviceType: '交换机',
      category: '安全审计',
      subCategory: '远程管理',
    },
    {
      id: 'cmd-hsw-snmp',
      name: '查看SNMP配置',
      target: '华为交换机',
      command: 'display snmp-agent sys-info version',
      description: '查看SNMP协议版本和团体字配置',
      os: 'VRP',
      brand: '华为',
      deviceType: '交换机',
      category: '安全审计',
      subCategory: 'SNMP',
    },
    {
      id: 'cmd-hsw-ntp',
      name: '查看NTP配置',
      target: '华为交换机',
      command: 'display ntp status',
      description: '查看NTP时间同步配置和状态',
      os: 'VRP',
      brand: '华为',
      deviceType: '交换机',
      category: '安全审计',
      subCategory: '时间同步',
    },
  ];
  commands.push(...huaweiSwitchCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // 1.2 H3C交换机 (Comware系统)
  const h3cSwitchCmds: SeedCommand[] = [
    {
      id: 'cmd-h3c-user-list',
      name: '查看用户列表',
      target: 'H3C交换机',
      command: 'display local-user',
      description: '查看所有本地用户账号信息',
      os: 'Comware',
      brand: 'H3C',
      deviceType: '交换机',
      category: '身份鉴别',
      subCategory: '用户管理',
    },
    {
      id: 'cmd-h3c-password-policy',
      name: '查看密码策略',
      target: 'H3C交换机',
      command: 'display password-control',
      description: '查看密码控制策略配置',
      os: 'Comware',
      brand: 'H3C',
      deviceType: '交换机',
      category: '身份鉴别',
      subCategory: '密码策略',
    },
    {
      id: 'cmd-h3c-acl',
      name: '查看ACL配置',
      target: 'H3C交换机',
      command: 'display acl all',
      description: '查看所有访问控制列表配置',
      os: 'Comware',
      brand: 'H3C',
      deviceType: '交换机',
      category: '访问控制',
      subCategory: 'ACL',
    },
    {
      id: 'cmd-h3c-vlan',
      name: '查看VLAN配置',
      target: 'H3C交换机',
      command: 'display vlan',
      description: '查看所有VLAN配置信息',
      os: 'Comware',
      brand: 'H3C',
      deviceType: '交换机',
      category: '网络架构',
      subCategory: 'VLAN',
    },
    {
      id: 'cmd-h3c-log',
      name: '查看日志配置',
      target: 'H3C交换机',
      command: 'display logbuffer',
      description: '查看日志缓冲区配置',
      os: 'Comware',
      brand: 'H3C',
      deviceType: '交换机',
      category: '安全审计',
      subCategory: '日志配置',
    },
    {
      id: 'cmd-h3c-ssh',
      name: '查看SSH配置',
      target: 'H3C交换机',
      command: 'display ssh server status',
      description: '查看SSH服务状态和配置',
      os: 'Comware',
      brand: 'H3C',
      deviceType: '交换机',
      category: '安全审计',
      subCategory: '远程管理',
    },
  ];
  commands.push(...h3cSwitchCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // 1.3 思科交换机 (IOS系统)
  const ciscoSwitchCmds: SeedCommand[] = [
    {
      id: 'cmd-csc-user-list',
      name: '查看用户列表',
      target: '思科交换机',
      command: 'show running-config | include username',
      description: '查看本地用户配置',
      os: 'IOS',
      brand: '思科',
      deviceType: '交换机',
      category: '身份鉴别',
      subCategory: '用户管理',
    },
    {
      id: 'cmd-csc-password-policy',
      name: '查看密码策略',
      target: '思科交换机',
      command: 'show running-config | include security passwords',
      description: '查看密码安全策略配置',
      os: 'IOS',
      brand: '思科',
      deviceType: '交换机',
      category: '身份鉴别',
      subCategory: '密码策略',
    },
    {
      id: 'cmd-csc-acl',
      name: '查看ACL配置',
      target: '思科交换机',
      command: 'show access-lists',
      description: '查看所有访问控制列表',
      os: 'IOS',
      brand: '思科',
      deviceType: '交换机',
      category: '访问控制',
      subCategory: 'ACL',
    },
    {
      id: 'cmd-csc-vlan',
      name: '查看VLAN配置',
      target: '思科交换机',
      command: 'show vlan brief',
      description: '查看VLAN简要信息',
      os: 'IOS',
      brand: '思科',
      deviceType: '交换机',
      category: '网络架构',
      subCategory: 'VLAN',
    },
    {
      id: 'cmd-csc-log',
      name: '查看日志配置',
      target: '思科交换机',
      command: 'show logging',
      description: '查看系统日志配置和状态',
      os: 'IOS',
      brand: '思科',
      deviceType: '交换机',
      category: '安全审计',
      subCategory: '日志配置',
    },
    {
      id: 'cmd-csc-ssh',
      name: '查看SSH配置',
      target: '思科交换机',
      command: 'show ip ssh',
      description: '查看SSH版本和配置信息',
      os: 'IOS',
      brand: '思科',
      deviceType: '交换机',
      category: '安全审计',
      subCategory: '远程管理',
    },
  ];
  commands.push(...ciscoSwitchCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 二、安全设备 - 防火墙
  // ========================

  // 2.1 深信服防火墙
  const sangforFwCmds: SeedCommand[] = [
    {
      id: 'cmd-sf-user-list',
      name: '查看用户列表',
      target: '深信服防火墙',
      command: 'show user all',
      description: '查看所有用户账号信息',
      os: 'SANGFOR',
      brand: '深信服',
      deviceType: '防火墙',
      category: '身份鉴别',
      subCategory: '用户管理',
    },
    {
      id: 'cmd-sf-password-policy',
      name: '查看密码策略',
      target: '深信服防火墙',
      command: 'show pwd-policy',
      description: '查看密码复杂度策略配置',
      os: 'SANGFOR',
      brand: '深信服',
      deviceType: '防火墙',
      category: '身份鉴别',
      subCategory: '密码策略',
    },
    {
      id: 'cmd-sf-acl',
      name: '查看访问策略',
      target: '深信服防火墙',
      command: 'show policy all',
      description: '查看所有访问控制策略',
      os: 'SANGFOR',
      brand: '深信服',
      deviceType: '防火墙',
      category: '访问控制',
      subCategory: '安全策略',
    },
    {
      id: 'cmd-sf-nat',
      name: '查看NAT配置',
      target: '深信服防火墙',
      command: 'show nat all',
      description: '查看NAT地址转换配置',
      os: 'SANGFOR',
      brand: '深信服',
      deviceType: '防火墙',
      category: '访问控制',
      subCategory: 'NAT',
    },
    {
      id: 'cmd-sf-log',
      name: '查看日志配置',
      target: '深信服防火墙',
      command: 'show log-setting',
      description: '查看日志服务器和审计配置',
      os: 'SANGFOR',
      brand: '深信服',
      deviceType: '防火墙',
      category: '安全审计',
      subCategory: '日志配置',
    },
    {
      id: 'cmd-sf-vpn',
      name: '查看VPN配置',
      target: '深信服防火墙',
      command: 'show vpn ipsec',
      description: '查看IPSec VPN配置信息',
      os: 'SANGFOR',
      brand: '深信服',
      deviceType: '防火墙',
      category: '通信传输',
      subCategory: 'VPN',
    },
  ];
  commands.push(...sangforFwCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // 2.2 天融信防火墙
  const topsecFwCmds: SeedCommand[] = [
    {
      id: 'cmd-ts-user-list',
      name: '查看用户列表',
      target: '天融信防火墙',
      command: 'show user',
      description: '查看所有用户账号信息',
      os: 'TOPSEC',
      brand: '天融信',
      deviceType: '防火墙',
      category: '身份鉴别',
      subCategory: '用户管理',
    },
    {
      id: 'cmd-ts-password-policy',
      name: '查看密码策略',
      target: '天融信防火墙',
      command: 'show password-policy',
      description: '查看密码安全策略配置',
      os: 'TOPSEC',
      brand: '天融信',
      deviceType: '防火墙',
      category: '身份鉴别',
      subCategory: '密码策略',
    },
    {
      id: 'cmd-ts-acl',
      name: '查看访问策略',
      target: '天融信防火墙',
      command: 'show policy',
      description: '查看所有访问控制策略',
      os: 'TOPSEC',
      brand: '天融信',
      deviceType: '防火墙',
      category: '访问控制',
      subCategory: '安全策略',
    },
    {
      id: 'cmd-ts-log',
      name: '查看日志配置',
      target: '天融信防火墙',
      command: 'show logging',
      description: '查看系统日志配置',
      os: 'TOPSEC',
      brand: '天融信',
      deviceType: '防火墙',
      category: '安全审计',
      subCategory: '日志配置',
    },
  ];
  commands.push(...topsecFwCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // 2.3 华为防火墙 (USG系列)
  const huaweiFwCmds: SeedCommand[] = [
    {
      id: 'cmd-hfw-user-list',
      name: '查看用户列表',
      target: '华为防火墙',
      command: 'display local-user',
      description: '查看所有本地用户账号信息',
      os: 'VRP',
      brand: '华为',
      deviceType: '防火墙',
      category: '身份鉴别',
      subCategory: '用户管理',
    },
    {
      id: 'cmd-hfw-password-policy',
      name: '查看密码策略',
      target: '华为防火墙',
      command: 'display password policy',
      description: '查看密码复杂度策略配置',
      os: 'VRP',
      brand: '华为',
      deviceType: '防火墙',
      category: '身份鉴别',
      subCategory: '密码策略',
    },
    {
      id: 'cmd-hfw-security-policy',
      name: '查看安全策略',
      target: '华为防火墙',
      command: 'display security-policy rule all',
      description: '查看所有安全策略规则',
      os: 'VRP',
      brand: '华为',
      deviceType: '防火墙',
      category: '访问控制',
      subCategory: '安全策略',
    },
    {
      id: 'cmd-hfw-nat',
      name: '查看NAT配置',
      target: '华为防火墙',
      command: 'display nat server',
      description: '查看NAT服务器映射配置',
      os: 'VRP',
      brand: '华为',
      deviceType: '防火墙',
      category: '访问控制',
      subCategory: 'NAT',
    },
    {
      id: 'cmd-hfw-log',
      name: '查看日志配置',
      target: '华为防火墙',
      command: 'display info-center',
      description: '查看日志中心和日志配置',
      os: 'VRP',
      brand: '华为',
      deviceType: '防火墙',
      category: '安全审计',
      subCategory: '日志配置',
    },
  ];
  commands.push(...huaweiFwCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 三、服务器 - Linux
  // ========================

  // 3.1 Linux通用命令
  const linuxCmds: SeedCommand[] = [
    {
      id: 'cmd-linux-user-list',
      name: '查看所有用户',
      target: 'Linux服务器',
      command: 'cat /etc/passwd',
      description: '查看系统所有用户账号信息',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '身份鉴别',
      subCategory: '用户管理',
    },
    {
      id: 'cmd-linux-password-policy',
      name: '查看密码策略',
      target: 'Linux服务器',
      command: 'cat /etc/login.defs | grep -E "PASS_MAX_DAYS|PASS_MIN_DAYS|PASS_MIN_LEN|PASS_WARN_AGE"',
      description: '查看密码有效期和复杂度策略',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '身份鉴别',
      subCategory: '密码策略',
    },
    {
      id: 'cmd-linux-pam-password',
      name: '查看PAM密码配置',
      target: 'Linux服务器',
      command: 'cat /etc/pam.d/system-auth',
      description: '查看PAM认证模块密码配置',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '身份鉴别',
      subCategory: 'PAM配置',
    },
    {
      id: 'cmd-linux-login-fail',
      name: '查看登录失败处理',
      target: 'Linux服务器',
      command: 'cat /etc/pam.d/sshd | grep -E "pam_tally|pam_faillock"',
      description: '查看登录失败锁定配置',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '身份鉴别',
      subCategory: '登录失败处理',
    },
    {
      id: 'cmd-linux-ssh-timeout',
      name: '查看SSH超时配置',
      target: 'Linux服务器',
      command: 'cat /etc/ssh/sshd_config | grep -E "ClientAliveInterval|ClientAliveCountMax|LoginGraceTime"',
      description: '查看SSH会话超时配置',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '身份鉴别',
      subCategory: '会话管理',
    },
    {
      id: 'cmd-linux-sudoers',
      name: '查看sudo权限',
      target: 'Linux服务器',
      command: 'cat /etc/sudoers',
      description: '查看sudo权限分配配置',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '访问控制',
      subCategory: '权限管理',
    },
    {
      id: 'cmd-linux-root-remote',
      name: '查看root远程登录',
      target: 'Linux服务器',
      command: 'cat /etc/ssh/sshd_config | grep PermitRootLogin',
      description: '查看是否允许root用户远程SSH登录',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '访问控制',
      subCategory: '远程访问',
    },
    {
      id: 'cmd-linux-firewall',
      name: '查看防火墙配置',
      target: 'Linux服务器',
      command: 'iptables -L -n',
      description: '查看iptables防火墙规则',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '访问控制',
      subCategory: '防火墙',
    },
    {
      id: 'cmd-linux-firewalld',
      name: '查看firewalld配置',
      target: 'Linux服务器',
      command: 'firewall-cmd --list-all',
      description: '查看firewalld防火墙配置',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '访问控制',
      subCategory: '防火墙',
    },
    {
      id: 'cmd-linux-audit',
      name: '查看审计服务状态',
      target: 'Linux服务器',
      command: 'service auditd status',
      description: '查看auditd审计服务运行状态',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '安全审计',
      subCategory: '审计服务',
    },
    {
      id: 'cmd-linux-audit-rules',
      name: '查看审计规则',
      target: 'Linux服务器',
      command: 'auditctl -l',
      description: '查看系统审计规则配置',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '安全审计',
      subCategory: '审计规则',
    },
    {
      id: 'cmd-linux-syslog',
      name: '查看系统日志配置',
      target: 'Linux服务器',
      command: 'cat /etc/rsyslog.conf',
      description: '查看rsyslog日志服务配置',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '安全审计',
      subCategory: '日志配置',
    },
    {
      id: 'cmd-linux-ports',
      name: '查看开放端口',
      target: 'Linux服务器',
      command: 'ss -tlnp',
      description: '查看系统监听端口和对应进程',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '入侵防范',
      subCategory: '端口管理',
    },
    {
      id: 'cmd-linux-services',
      name: '查看系统服务',
      target: 'Linux服务器',
      command: 'systemctl list-unit-files --type=service --state=enabled',
      description: '查看已启用的系统服务列表',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '入侵防范',
      subCategory: '服务管理',
    },
    {
      id: 'cmd-linux-kernel',
      name: '查看内核版本',
      target: 'Linux服务器',
      command: 'uname -a',
      description: '查看操作系统内核版本信息',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '入侵防范',
      subCategory: '系统版本',
    },
    {
      id: 'cmd-linux-updates',
      name: '查看系统更新',
      target: 'Linux服务器',
      command: 'rpm -qa --last | head -20',
      description: '查看最近安装的软件包更新',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '入侵防范',
      subCategory: '补丁管理',
    },
  ];
  commands.push(...linuxCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 四、服务器 - Windows
  // ========================

  const windowsCmds: SeedCommand[] = [
    {
      id: 'cmd-win-user-list',
      name: '查看用户列表',
      target: 'Windows服务器',
      command: 'net user',
      description: '查看所有本地用户账号',
      os: 'Windows',
      brand: '微软',
      deviceType: '服务器',
      category: '身份鉴别',
      subCategory: '用户管理',
    },
    {
      id: 'cmd-win-password-policy',
      name: '查看密码策略',
      target: 'Windows服务器',
      command: 'net accounts',
      description: '查看密码策略和锁定策略配置',
      os: 'Windows',
      brand: '微软',
      deviceType: '服务器',
      category: '身份鉴别',
      subCategory: '密码策略',
    },
    {
      id: 'cmd-win-admin-group',
      name: '查看管理员组成员',
      target: 'Windows服务器',
      command: 'net localgroup administrators',
      description: '查看本地管理员组成员列表',
      os: 'Windows',
      brand: '微软',
      deviceType: '服务器',
      category: '访问控制',
      subCategory: '权限管理',
    },
    {
      id: 'cmd-win-remote-desktop',
      name: '查看远程桌面配置',
      target: 'Windows服务器',
      command: 'reg query "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server" /v fDenyTSConnections',
      description: '查看远程桌面是否启用',
      os: 'Windows',
      brand: '微软',
      deviceType: '服务器',
      category: '访问控制',
      subCategory: '远程访问',
    },
    {
      id: 'cmd-win-firewall',
      name: '查看防火墙配置',
      target: 'Windows服务器',
      command: 'netsh advfirewall show allprofiles',
      description: '查看Windows防火墙所有配置文件状态',
      os: 'Windows',
      brand: '微软',
      deviceType: '服务器',
      category: '访问控制',
      subCategory: '防火墙',
    },
    {
      id: 'cmd-win-audit-policy',
      name: '查看审核策略',
      target: 'Windows服务器',
      command: 'auditpol /get /category:*',
      description: '查看系统审核策略配置',
      os: 'Windows',
      brand: '微软',
      deviceType: '服务器',
      category: '安全审计',
      subCategory: '审核策略',
    },
    {
      id: 'cmd-win-event-log',
      name: '查看事件日志配置',
      target: 'Windows服务器',
      command: 'wevtutil gl System',
      description: '查看系统事件日志配置',
      os: 'Windows',
      brand: '微软',
      deviceType: '服务器',
      category: '安全审计',
      subCategory: '日志配置',
    },
    {
      id: 'cmd-win-ports',
      name: '查看开放端口',
      target: 'Windows服务器',
      command: 'netstat -ano',
      description: '查看网络连接和监听端口',
      os: 'Windows',
      brand: '微软',
      deviceType: '服务器',
      category: '入侵防范',
      subCategory: '端口管理',
    },
    {
      id: 'cmd-win-services',
      name: '查看系统服务',
      target: 'Windows服务器',
      command: 'sc query state= all',
      description: '查看所有系统服务状态',
      os: 'Windows',
      brand: '微软',
      deviceType: '服务器',
      category: '入侵防范',
      subCategory: '服务管理',
    },
    {
      id: 'cmd-win-updates',
      name: '查看已安装更新',
      target: 'Windows服务器',
      command: 'Get-HotFix | Select-Object HotFixID,InstalledOn',
      description: '查看已安装的补丁更新列表',
      os: 'Windows',
      brand: '微软',
      deviceType: '服务器',
      category: '入侵防范',
      subCategory: '补丁管理',
    },
    {
      id: 'cmd-win-os-version',
      name: '查看系统版本',
      target: 'Windows服务器',
      command: 'ver',
      description: '查看Windows操作系统版本',
      os: 'Windows',
      brand: '微软',
      deviceType: '服务器',
      category: '入侵防范',
      subCategory: '系统版本',
    },
  ];
  commands.push(...windowsCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 五、数据库 - MySQL
  // ========================

  const mysqlCmds: SeedCommand[] = [
    {
      id: 'cmd-mysql-user-list',
      name: '查看用户列表',
      target: 'MySQL数据库',
      command: "SELECT user, host, authentication_string FROM mysql.user;",
      description: '查看所有MySQL用户账号和认证方式',
      os: 'MySQL',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '身份鉴别',
      subCategory: '用户管理',
    },
    {
      id: 'cmd-mysql-password-policy',
      name: '查看密码策略',
      target: 'MySQL数据库',
      command: "SHOW VARIABLES LIKE 'validate_password%';",
      description: '查看密码复杂度验证策略配置',
      os: 'MySQL',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '身份鉴别',
      subCategory: '密码策略',
    },
    {
      id: 'cmd-mysql-password-expire',
      name: '查看密码过期策略',
      target: 'MySQL数据库',
      command: "SHOW VARIABLES LIKE 'default_password_lifetime';",
      description: '查看密码默认过期时间配置',
      os: 'MySQL',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '身份鉴别',
      subCategory: '密码策略',
    },
    {
      id: 'cmd-mysql-privileges',
      name: '查看用户权限',
      target: 'MySQL数据库',
      command: "SHOW GRANTS FOR '用户名'@'主机名';",
      description: '查看指定用户的权限授予情况',
      os: 'MySQL',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '访问控制',
      subCategory: '权限管理',
    },
    {
      id: 'cmd-mysql-ssl',
      name: '查看SSL配置',
      target: 'MySQL数据库',
      command: "SHOW VARIABLES LIKE '%ssl%';",
      description: '查看MySQL SSL/TLS加密配置',
      os: 'MySQL',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '通信传输',
      subCategory: '加密传输',
    },
    {
      id: 'cmd-mysql-log',
      name: '查看日志配置',
      target: 'MySQL数据库',
      command: "SHOW VARIABLES LIKE '%log%';",
      description: '查看MySQL日志相关配置',
      os: 'MySQL',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '安全审计',
      subCategory: '日志配置',
    },
    {
      id: 'cmd-mysql-audit',
      name: '查看审计插件',
      target: 'MySQL数据库',
      command: "SHOW PLUGINS;",
      description: '查看已安装的审计插件',
      os: 'MySQL',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '安全审计',
      subCategory: '审计插件',
    },
    {
      id: 'cmd-mysql-version',
      name: '查看版本信息',
      target: 'MySQL数据库',
      command: "SELECT VERSION();",
      description: '查看MySQL数据库版本号',
      os: 'MySQL',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '入侵防范',
      subCategory: '版本信息',
    },
  ];
  commands.push(...mysqlCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 六、数据库 - Oracle
  // ========================

  const oracleCmds: SeedCommand[] = [
    {
      id: 'cmd-ora-user-list',
      name: '查看用户列表',
      target: 'Oracle数据库',
      command: "SELECT username, account_status, expiry_date FROM dba_users;",
      description: '查看所有Oracle用户账号状态',
      os: 'Oracle',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '身份鉴别',
      subCategory: '用户管理',
    },
    {
      id: 'cmd-ora-password-policy',
      name: '查看密码策略',
      target: 'Oracle数据库',
      command: "SELECT profile, resource_name, limit FROM dba_profiles WHERE resource_type='PASSWORD';",
      description: '查看密码策略配置文件',
      os: 'Oracle',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '身份鉴别',
      subCategory: '密码策略',
    },
    {
      id: 'cmd-ora-privileges',
      name: '查看用户权限',
      target: 'Oracle数据库',
      command: "SELECT * FROM dba_sys_privs WHERE grantee='用户名';",
      description: '查看指定用户的系统权限',
      os: 'Oracle',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '访问控制',
      subCategory: '权限管理',
    },
    {
      id: 'cmd-ora-roles',
      name: '查看角色权限',
      target: 'Oracle数据库',
      command: "SELECT * FROM dba_role_privs WHERE grantee='用户名';",
      description: '查看指定用户被授予的角色',
      os: 'Oracle',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '访问控制',
      subCategory: '角色管理',
    },
    {
      id: 'cmd-ora-audit',
      name: '查看审计配置',
      target: 'Oracle数据库',
      command: "SELECT parameter, value FROM v$option WHERE parameter='Unified Auditing';",
      description: '查看统一审计功能是否启用',
      os: 'Oracle',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '安全审计',
      subCategory: '审计配置',
    },
    {
      id: 'cmd-ora-audit-trail',
      name: '查看审计记录',
      target: 'Oracle数据库',
      command: "SELECT * FROM unified_audit_trail WHERE ROWNUM <= 10;",
      description: '查看统一审计日志记录',
      os: 'Oracle',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '安全审计',
      subCategory: '审计日志',
    },
    {
      id: 'cmd-ora-encryption',
      name: '查看加密配置',
      target: 'Oracle数据库',
      command: "SELECT * FROM v$encryption_wallet;",
      description: '查看加密钱包配置状态',
      os: 'Oracle',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '通信传输',
      subCategory: '数据加密',
    },
    {
      id: 'cmd-ora-version',
      name: '查看版本信息',
      target: 'Oracle数据库',
      command: "SELECT banner FROM v$version;",
      description: '查看Oracle数据库版本信息',
      os: 'Oracle',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '入侵防范',
      subCategory: '版本信息',
    },
  ];
  commands.push(...oracleCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 七、数据库 - SQL Server
  // ========================

  const sqlserverCmds: SeedCommand[] = [
    {
      id: 'cmd-mssql-user-list',
      name: '查看用户列表',
      target: 'SQL Server数据库',
      command: "SELECT name, type_desc, is_disabled FROM sys.server_principals WHERE type IN ('S','U','G');",
      description: '查看所有SQL Server登录账号',
      os: 'SQL Server',
      brand: '微软',
      deviceType: '数据库',
      category: '身份鉴别',
      subCategory: '用户管理',
    },
    {
      id: 'cmd-mssql-password-policy',
      name: '查看密码策略',
      target: 'SQL Server数据库',
      command: "SELECT name, is_policy_checked, is_expiration_checked FROM sys.sql_logins;",
      description: '查看SQL登录账号的密码策略和过期检查',
      os: 'SQL Server',
      brand: '微软',
      deviceType: '数据库',
      category: '身份鉴别',
      subCategory: '密码策略',
    },
    {
      id: 'cmd-mssql-privileges',
      name: '查看用户权限',
      target: 'SQL Server数据库',
      command: "SELECT * FROM sys.server_permissions WHERE grantee_principal_id=USER_ID('用户名');",
      description: '查看指定用户的服务器级权限',
      os: 'SQL Server',
      brand: '微软',
      deviceType: '数据库',
      category: '访问控制',
      subCategory: '权限管理',
    },
    {
      id: 'cmd-mssql-roles',
      name: '查看角色成员',
      target: 'SQL Server数据库',
      command: "SELECT DP1.name AS DatabaseRoleName, DP2.name AS DatabaseUserName FROM sys.database_role_members DRM INNER JOIN sys.database_principals DP1 ON DRM.role_principal_id = DP1.principal_id INNER JOIN sys.database_principals DP2 ON DRM.member_principal_id = DP2.principal_id;",
      description: '查看数据库角色和成员关系',
      os: 'SQL Server',
      brand: '微软',
      deviceType: '数据库',
      category: '访问控制',
      subCategory: '角色管理',
    },
    {
      id: 'cmd-mssql-audit',
      name: '查看审计配置',
      target: 'SQL Server数据库',
      command: "SELECT * FROM sys.server_audits;",
      description: '查看服务器级审计规范',
      os: 'SQL Server',
      brand: '微软',
      deviceType: '数据库',
      category: '安全审计',
      subCategory: '审计配置',
    },
    {
      id: 'cmd-mssql-encryption',
      name: '查看加密配置',
      target: 'SQL Server数据库',
      command: "SELECT name, is_encrypted FROM sys.databases;",
      description: '查看数据库透明数据加密状态',
      os: 'SQL Server',
      brand: '微软',
      deviceType: '数据库',
      category: '通信传输',
      subCategory: '数据加密',
    },
    {
      id: 'cmd-mssql-version',
      name: '查看版本信息',
      target: 'SQL Server数据库',
      command: "SELECT @@VERSION;",
      description: '查看SQL Server版本和补丁信息',
      os: 'SQL Server',
      brand: '微软',
      deviceType: '数据库',
      category: '入侵防范',
      subCategory: '版本信息',
    },
  ];
  commands.push(...sqlserverCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 八、数据库 - PostgreSQL
  // ========================

  const pgCmds: SeedCommand[] = [
    {
      id: 'cmd-pg-user-list',
      name: '查看用户列表',
      target: 'PostgreSQL数据库',
      command: "SELECT rolname, rolsuper, rolcanlogin, rolcreatedb FROM pg_roles;",
      description: '查看所有数据库角色和用户',
      os: 'PostgreSQL',
      brand: 'PostgreSQL',
      deviceType: '数据库',
      category: '身份鉴别',
      subCategory: '用户管理',
    },
    {
      id: 'cmd-pg-password-policy',
      name: '查看密码策略',
      target: 'PostgreSQL数据库',
      command: "SHOW password_encryption;",
      description: '查看密码加密方式配置',
      os: 'PostgreSQL',
      brand: 'PostgreSQL',
      deviceType: '数据库',
      category: '身份鉴别',
      subCategory: '密码策略',
    },
    {
      id: 'cmd-pg-hba',
      name: '查看认证配置',
      target: 'PostgreSQL数据库',
      command: "SELECT * FROM pg_hba_file_rules;",
      description: '查看客户端认证配置文件规则',
      os: 'PostgreSQL',
      brand: 'PostgreSQL',
      deviceType: '数据库',
      category: '身份鉴别',
      subCategory: '认证配置',
    },
    {
      id: 'cmd-pg-privileges',
      name: '查看用户权限',
      target: 'PostgreSQL数据库',
      command: "SELECT grantee, table_schema, table_name, privilege_type FROM information_schema.role_table_grants WHERE grantee NOT IN ('PUBLIC');",
      description: '查看数据库对象权限分配',
      os: 'PostgreSQL',
      brand: 'PostgreSQL',
      deviceType: '数据库',
      category: '访问控制',
      subCategory: '权限管理',
    },
    {
      id: 'cmd-pg-ssl',
      name: '查看SSL配置',
      target: 'PostgreSQL数据库',
      command: "SHOW ssl;",
      description: '查看SSL连接配置状态',
      os: 'PostgreSQL',
      brand: 'PostgreSQL',
      deviceType: '数据库',
      category: '通信传输',
      subCategory: '加密传输',
    },
    {
      id: 'cmd-pg-log',
      name: '查看日志配置',
      target: 'PostgreSQL数据库',
      command: "SHOW logging_collector; SHOW log_directory; SHOW log_filename;",
      description: '查看日志收集器和日志文件配置',
      os: 'PostgreSQL',
      brand: 'PostgreSQL',
      deviceType: '数据库',
      category: '安全审计',
      subCategory: '日志配置',
    },
    {
      id: 'cmd-pg-audit',
      name: '查看审计扩展',
      target: 'PostgreSQL数据库',
      command: "SELECT * FROM pg_available_extensions WHERE name LIKE '%audit%';",
      description: '查看可用的审计扩展',
      os: 'PostgreSQL',
      brand: 'PostgreSQL',
      deviceType: '数据库',
      category: '安全审计',
      subCategory: '审计扩展',
    },
    {
      id: 'cmd-pg-version',
      name: '查看版本信息',
      target: 'PostgreSQL数据库',
      command: "SELECT version();",
      description: '查看PostgreSQL版本信息',
      os: 'PostgreSQL',
      brand: 'PostgreSQL',
      deviceType: '数据库',
      category: '入侵防范',
      subCategory: '版本信息',
    },
  ];
  commands.push(...pgCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 九、中间件 - Nginx
  // ========================

  const nginxCmds: SeedCommand[] = [
    {
      id: 'cmd-nginx-config',
      name: '查看主配置文件',
      target: 'Nginx',
      command: 'cat /etc/nginx/nginx.conf',
      description: '查看Nginx主配置文件内容',
      os: 'Linux',
      brand: 'Nginx',
      deviceType: '中间件',
      category: '安全配置',
      subCategory: '配置文件',
    },
    {
      id: 'cmd-nginx-ssl',
      name: '查看SSL配置',
      target: 'Nginx',
      command: "grep -r 'ssl_' /etc/nginx/conf.d/",
      description: '查看Nginx SSL/TLS配置',
      os: 'Linux',
      brand: 'Nginx',
      deviceType: '中间件',
      category: '通信传输',
      subCategory: 'SSL配置',
    },
    {
      id: 'cmd-nginx-server',
      name: '查看虚拟主机配置',
      target: 'Nginx',
      command: 'cat /etc/nginx/conf.d/*.conf',
      description: '查看Nginx虚拟主机配置文件',
      os: 'Linux',
      brand: 'Nginx',
      deviceType: '中间件',
      category: '安全配置',
      subCategory: '虚拟主机',
    },
    {
      id: 'cmd-nginx-access-log',
      name: '查看访问日志配置',
      target: 'Nginx',
      command: "grep -E 'access_log|error_log' /etc/nginx/nginx.conf",
      description: '查看Nginx访问日志和错误日志配置',
      os: 'Linux',
      brand: 'Nginx',
      deviceType: '中间件',
      category: '安全审计',
      subCategory: '日志配置',
    },
    {
      id: 'cmd-nginx-version',
      name: '查看版本信息',
      target: 'Nginx',
      command: 'nginx -v',
      description: '查看Nginx版本号',
      os: 'Linux',
      brand: 'Nginx',
      deviceType: '中间件',
      category: '入侵防范',
      subCategory: '版本信息',
    },
    {
      id: 'cmd-nginx-status',
      name: '查看运行状态',
      target: 'Nginx',
      command: 'systemctl status nginx',
      description: '查看Nginx服务运行状态',
      os: 'Linux',
      brand: 'Nginx',
      deviceType: '中间件',
      category: '入侵防范',
      subCategory: '运行状态',
    },
  ];
  commands.push(...nginxCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 十、中间件 - Apache
  // ========================

  const apacheCmds: SeedCommand[] = [
    {
      id: 'cmd-apache-config',
      name: '查看主配置文件',
      target: 'Apache',
      command: 'cat /etc/httpd/conf/httpd.conf',
      description: '查看Apache主配置文件内容',
      os: 'Linux',
      brand: 'Apache',
      deviceType: '中间件',
      category: '安全配置',
      subCategory: '配置文件',
    },
    {
      id: 'cmd-apache-ssl',
      name: '查看SSL配置',
      target: 'Apache',
      command: "grep -r 'SSLEngine' /etc/httpd/conf.d/",
      description: '查看Apache SSL配置',
      os: 'Linux',
      brand: 'Apache',
      deviceType: '中间件',
      category: '通信传输',
      subCategory: 'SSL配置',
    },
    {
      id: 'cmd-apache-modules',
      name: '查看加载模块',
      target: 'Apache',
      command: 'httpd -M',
      description: '查看Apache已加载的模块列表',
      os: 'Linux',
      brand: 'Apache',
      deviceType: '中间件',
      category: '安全配置',
      subCategory: '模块管理',
    },
    {
      id: 'cmd-apache-version',
      name: '查看版本信息',
      target: 'Apache',
      command: 'httpd -v',
      description: '查看Apache版本号',
      os: 'Linux',
      brand: 'Apache',
      deviceType: '中间件',
      category: '入侵防范',
      subCategory: '版本信息',
    },
  ];
  commands.push(...apacheCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 十一、中间件 - Tomcat
  // ========================

  const tomcatCmds: SeedCommand[] = [
    {
      id: 'cmd-tomcat-config',
      name: '查看主配置文件',
      target: 'Tomcat',
      command: 'cat /usr/local/tomcat/conf/server.xml',
      description: '查看Tomcat服务器配置文件',
      os: 'Linux',
      brand: 'Apache',
      deviceType: '中间件',
      category: '安全配置',
      subCategory: '配置文件',
    },
    {
      id: 'cmd-tomcat-user',
      name: '查看用户配置',
      target: 'Tomcat',
      command: 'cat /usr/local/tomcat/conf/tomcat-users.xml',
      description: '查看Tomcat用户和角色配置',
      os: 'Linux',
      brand: 'Apache',
      deviceType: '中间件',
      category: '身份鉴别',
      subCategory: '用户管理',
    },
    {
      id: 'cmd-tomcat-ssl',
      name: '查看SSL配置',
      target: 'Tomcat',
      command: "grep -A5 'SSL' /usr/local/tomcat/conf/server.xml",
      description: '查看Tomcat SSL连接器配置',
      os: 'Linux',
      brand: 'Apache',
      deviceType: '中间件',
      category: '通信传输',
      subCategory: 'SSL配置',
    },
    {
      id: 'cmd-tomcat-log',
      name: '查看日志配置',
      target: 'Tomcat',
      command: 'cat /usr/local/tomcat/conf/logging.properties',
      description: '查看Tomcat日志配置',
      os: 'Linux',
      brand: 'Apache',
      deviceType: '中间件',
      category: '安全审计',
      subCategory: '日志配置',
    },
    {
      id: 'cmd-tomcat-version',
      name: '查看版本信息',
      target: 'Tomcat',
      command: '/usr/local/tomcat/bin/version.sh',
      description: '查看Tomcat版本号',
      os: 'Linux',
      brand: 'Apache',
      deviceType: '中间件',
      category: '入侵防范',
      subCategory: '版本信息',
    },
  ];
  commands.push(...tomcatCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 十二、中间件 - WebLogic
  // ========================

  const weblogicCmds: SeedCommand[] = [
    {
      id: 'cmd-wl-config',
      name: '查看域配置文件',
      target: 'WebLogic',
      command: 'cat /u01/oracle/user_projects/domains/base_domain/config/config.xml',
      description: '查看WebLogic域配置文件',
      os: 'Linux',
      brand: 'Oracle',
      deviceType: '中间件',
      category: '安全配置',
      subCategory: '配置文件',
    },
    {
      id: 'cmd-wl-ssl',
      name: '查看SSL配置',
      target: 'WebLogic',
      command: "grep -A10 'ssl' /u01/oracle/user_projects/domains/base_domain/config/config.xml",
      description: '查看WebLogic SSL配置',
      os: 'Linux',
      brand: 'Oracle',
      deviceType: '中间件',
      category: '通信传输',
      subCategory: 'SSL配置',
    },
    {
      id: 'cmd-wl-log',
      name: '查看日志配置',
      target: 'WebLogic',
      command: "grep -A5 'log' /u01/oracle/user_projects/domains/base_domain/config/config.xml",
      description: '查看WebLogic日志配置',
      os: 'Linux',
      brand: 'Oracle',
      deviceType: '中间件',
      category: '安全审计',
      subCategory: '日志配置',
    },
    {
      id: 'cmd-wl-version',
      name: '查看版本信息',
      target: 'WebLogic',
      command: 'java weblogic.version',
      description: '查看WebLogic版本号',
      os: 'Linux',
      brand: 'Oracle',
      deviceType: '中间件',
      category: '入侵防范',
      subCategory: '版本信息',
    },
  ];
  commands.push(...weblogicCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 十三、数据库 - Redis
  // ========================

  const redisCmds: SeedCommand[] = [
    {
      id: 'cmd-redis-user-list',
      name: '查看用户列表',
      target: 'Redis数据库',
      command: 'ACL LIST',
      description: '查看所有Redis ACL用户账号',
      os: 'Redis',
      brand: 'Redis',
      deviceType: '数据库',
      category: '身份鉴别',
      subCategory: '用户管理',
    },
    {
      id: 'cmd-redis-password',
      name: '查看密码配置',
      target: 'Redis数据库',
      command: 'CONFIG GET requirepass',
      description: '查看Redis密码认证配置',
      os: 'Redis',
      brand: 'Redis',
      deviceType: '数据库',
      category: '身份鉴别',
      subCategory: '密码策略',
    },
    {
      id: 'cmd-redis-acl',
      name: '查看ACL权限',
      target: 'Redis数据库',
      command: 'ACL WHOAMI',
      description: '查看当前连接用户的权限',
      os: 'Redis',
      brand: 'Redis',
      deviceType: '数据库',
      category: '访问控制',
      subCategory: '权限管理',
    },
    {
      id: 'cmd-redis-command',
      name: '查看命令禁用',
      target: 'Redis数据库',
      command: 'ACL GETUSER default',
      description: '查看默认用户的命令权限和禁用命令',
      os: 'Redis',
      brand: 'Redis',
      deviceType: '数据库',
      category: '访问控制',
      subCategory: '命令控制',
    },
    {
      id: 'cmd-redis-bind',
      name: '查看绑定地址',
      target: 'Redis数据库',
      command: 'CONFIG GET bind',
      description: '查看Redis监听绑定地址',
      os: 'Redis',
      brand: 'Redis',
      deviceType: '数据库',
      category: '入侵防范',
      subCategory: '网络配置',
    },
    {
      id: 'cmd-redis-port',
      name: '查看端口配置',
      target: 'Redis数据库',
      command: 'CONFIG GET port',
      description: '查看Redis监听端口',
      os: 'Redis',
      brand: 'Redis',
      deviceType: '数据库',
      category: '入侵防范',
      subCategory: '端口管理',
    },
    {
      id: 'cmd-redis-log',
      name: '查看日志配置',
      target: 'Redis数据库',
      command: 'CONFIG GET logfile CONFIG GET loglevel',
      description: '查看Redis日志文件和日志级别',
      os: 'Redis',
      brand: 'Redis',
      deviceType: '数据库',
      category: '安全审计',
      subCategory: '日志配置',
    },
    {
      id: 'cmd-redis-version',
      name: '查看版本信息',
      target: 'Redis数据库',
      command: 'INFO server',
      description: '查看Redis服务器版本和运行信息',
      os: 'Redis',
      brand: 'Redis',
      deviceType: '数据库',
      category: '入侵防范',
      subCategory: '版本信息',
    },
  ];
  commands.push(...redisCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 十四、中间件 - IIS
  // ========================

  const iisCmds: SeedCommand[] = [
    {
      id: 'cmd-iis-config',
      name: '查看应用程序池',
      target: 'IIS服务器',
      command: 'Get-WebConfigurationProperty -Filter system.applicationHost/applicationPools/* -Name name',
      description: '查看所有应用程序池配置',
      os: 'Windows',
      brand: '微软',
      deviceType: '中间件',
      category: '安全配置',
      subCategory: '应用程序池',
    },
    {
      id: 'cmd-iis-ssl',
      name: '查看SSL绑定',
      target: 'IIS服务器',
      command: 'Get-WebBinding -Protocol https',
      description: '查看IIS HTTPS绑定和SSL证书配置',
      os: 'Windows',
      brand: '微软',
      deviceType: '中间件',
      category: '通信传输',
      subCategory: 'SSL配置',
    },
    {
      id: 'cmd-iis-auth',
      name: '查看身份验证',
      target: 'IIS服务器',
      command: 'Get-WebConfigurationProperty -Filter system.webServer/security/authentication/* -Name enabled',
      description: '查看IIS身份验证方式配置',
      os: 'Windows',
      brand: '微软',
      deviceType: '中间件',
      category: '身份鉴别',
      subCategory: '认证配置',
    },
    {
      id: 'cmd-iis-log',
      name: '查看日志配置',
      target: 'IIS服务器',
      command: 'Get-WebConfigurationProperty -Filter system.applicationHost/sites/siteDefaults/logFile -Name directory,logFormat,period',
      description: '查看IIS日志文件配置',
      os: 'Windows',
      brand: '微软',
      deviceType: '中间件',
      category: '安全审计',
      subCategory: '日志配置',
    },
    {
      id: 'cmd-iis-ip',
      name: '查看IP限制',
      target: 'IIS服务器',
      command: 'Get-WebConfigurationProperty -Filter system.webServer/security/ipSecurity -Name allowUnlisted',
      description: '查看IIS IP地址限制配置',
      os: 'Windows',
      brand: '微软',
      deviceType: '中间件',
      category: '访问控制',
      subCategory: 'IP限制',
    },
    {
      id: 'cmd-iis-version',
      name: '查看版本信息',
      target: 'IIS服务器',
      command: 'Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\InetStp\\ | Select-Object VersionString',
      description: '查看IIS版本号',
      os: 'Windows',
      brand: '微软',
      deviceType: '中间件',
      category: '入侵防范',
      subCategory: '版本信息',
    },
  ];
  commands.push(...iisCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 十五、容器安全 - Docker
  // ========================

  const dockerCmds: SeedCommand[] = [
    {
      id: 'cmd-docker-version',
      name: '查看Docker版本',
      target: 'Docker容器',
      command: 'docker version',
      description: '查看Docker客户端和服务端版本',
      os: 'Linux',
      brand: '通用',
      deviceType: '容器',
      category: '入侵防范',
      subCategory: '版本信息',
    },
    {
      id: 'cmd-docker-user',
      name: '查看容器用户',
      target: 'Docker容器',
      command: 'docker inspect --format "{{.Config.User}}" 容器名',
      description: '查看容器运行时的用户身份',
      os: 'Linux',
      brand: '通用',
      deviceType: '容器',
      category: '身份鉴别',
      subCategory: '用户管理',
    },
    {
      id: 'cmd-docker-privileged',
      name: '查看特权容器',
      target: 'Docker容器',
      command: 'docker inspect --format "{{.HostConfig.Privileged}}" 容器名',
      description: '查看容器是否以特权模式运行',
      os: 'Linux',
      brand: '通用',
      deviceType: '容器',
      category: '访问控制',
      subCategory: '权限管理',
    },
    {
      id: 'cmd-docker-network',
      name: '查看网络配置',
      target: 'Docker容器',
      command: 'docker network ls && docker inspect 网络名',
      description: '查看Docker网络配置和隔离情况',
      os: 'Linux',
      brand: '通用',
      deviceType: '容器',
      category: '网络架构',
      subCategory: '网络隔离',
    },
    {
      id: 'cmd-docker-volume',
      name: '查看挂载卷',
      target: 'Docker容器',
      command: 'docker inspect --format "{{json .Mounts}}" 容器名',
      description: '查看容器挂载的目录和文件',
      os: 'Linux',
      brand: '通用',
      deviceType: '容器',
      category: '访问控制',
      subCategory: '挂载安全',
    },
    {
      id: 'cmd-docker-capabilities',
      name: '查看Capabilities',
      target: 'Docker容器',
      command: 'docker inspect --format "{{.HostConfig.CapAdd}}" 容器名',
      description: '查看容器添加的Linux Capabilities',
      os: 'Linux',
      brand: '通用',
      deviceType: '容器',
      category: '访问控制',
      subCategory: '权限管理',
    },
    {
      id: 'cmd-docker-seccomp',
      name: '查看安全配置',
      target: 'Docker容器',
      command: 'docker inspect --format "{{.HostConfig.SecurityOpt}}" 容器名',
      description: '查看容器Seccomp和AppArmor安全配置',
      os: 'Linux',
      brand: '通用',
      deviceType: '容器',
      category: '安全配置',
      subCategory: '安全策略',
    },
    {
      id: 'cmd-docker-content-trust',
      name: '查看镜像信任',
      target: 'Docker容器',
      command: 'echo $DOCKER_CONTENT_TRUST',
      description: '查看Docker镜像内容信任是否启用',
      os: 'Linux',
      brand: '通用',
      deviceType: '容器',
      category: '安全配置',
      subCategory: '镜像安全',
    },
  ];
  commands.push(...dockerCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 十六、容器编排 - Kubernetes
  // ========================

  const k8sCmds: SeedCommand[] = [
    {
      id: 'cmd-k8s-version',
      name: '查看集群版本',
      target: 'Kubernetes',
      command: 'kubectl version --short',
      description: '查看Kubernetes集群版本',
      os: 'Linux',
      brand: '通用',
      deviceType: '容器编排',
      category: '入侵防范',
      subCategory: '版本信息',
    },
    {
      id: 'cmd-k8s-rbac',
      name: '查看RBAC配置',
      target: 'Kubernetes',
      command: 'kubectl get clusterrolebindings -o wide',
      description: '查看集群角色绑定和权限分配',
      os: 'Linux',
      brand: '通用',
      deviceType: '容器编排',
      category: '访问控制',
      subCategory: '权限管理',
    },
    {
      id: 'cmd-k8s-audit',
      name: '查看审计日志',
      target: 'Kubernetes',
      command: 'kubectl get --raw /apis/auditregistration.k8s.io/v1alpha1/auditsinks',
      description: '查看Kubernetes审计日志配置',
      os: 'Linux',
      brand: '通用',
      deviceType: '容器编排',
      category: '安全审计',
      subCategory: '审计配置',
    },
    {
      id: 'cmd-k8s-network-policy',
      name: '查看网络策略',
      target: 'Kubernetes',
      command: 'kubectl get networkpolicy --all-namespaces',
      description: '查看Kubernetes网络策略配置',
      os: 'Linux',
      brand: '通用',
      deviceType: '容器编排',
      category: '网络架构',
      subCategory: '网络隔离',
    },
    {
      id: 'cmd-k8s-pod-security',
      name: '查看Pod安全策略',
      target: 'Kubernetes',
      command: 'kubectl get psp',
      description: '查看Pod安全策略配置',
      os: 'Linux',
      brand: '通用',
      deviceType: '容器编排',
      category: '安全配置',
      subCategory: '安全策略',
    },
    {
      id: 'cmd-k8s-secrets',
      name: '查看Secrets',
      target: 'Kubernetes',
      command: 'kubectl get secrets --all-namespaces',
      description: '查看Kubernetes Secrets配置',
      os: 'Linux',
      brand: '通用',
      deviceType: '容器编排',
      category: '安全配置',
      subCategory: '密钥管理',
    },
    {
      id: 'cmd-k8s-service-account',
      name: '查看服务账号',
      target: 'Kubernetes',
      command: 'kubectl get serviceaccounts --all-namespaces',
      description: '查看Kubernetes服务账号列表',
      os: 'Linux',
      brand: '通用',
      deviceType: '容器编排',
      category: '身份鉴别',
      subCategory: '用户管理',
    },
    {
      id: 'cmd-k8s-etcd',
      name: '查看etcd加密',
      target: 'Kubernetes',
      command: 'kubectl get --raw /api/v1/namespaces/kube-system/secrets',
      description: '查看etcd数据加密配置',
      os: 'Linux',
      brand: '通用',
      deviceType: '容器编排',
      category: '通信传输',
      subCategory: '数据加密',
    },
  ];
  commands.push(...k8sCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 十七、交换机补充 - DHCP Snooping/802.1X/MAC安全
  // ========================

  const switchSupplementCmds: SeedCommand[] = [
    {
      id: 'cmd-hsw-dhcp-snooping',
      name: '查看DHCP Snooping',
      target: '华为交换机',
      command: 'display dhcp snooping configuration',
      description: '查看DHCP Snooping防欺骗配置',
      os: 'VRP',
      brand: '华为',
      deviceType: '交换机',
      category: '入侵防范',
      subCategory: 'DHCP安全',
    },
    {
      id: 'cmd-hsw-802.1x',
      name: '查看802.1X认证',
      target: '华为交换机',
      command: 'display dot1x',
      description: '查看802.1X端口认证配置',
      os: 'VRP',
      brand: '华为',
      deviceType: '交换机',
      category: '身份鉴别',
      subCategory: '端口认证',
    },
    {
      id: 'cmd-hsw-mac-security',
      name: '查看MAC地址安全',
      target: '华为交换机',
      command: 'display mac-address',
      description: '查看MAC地址表和安全绑定',
      os: 'VRP',
      brand: '华为',
      deviceType: '交换机',
      category: '访问控制',
      subCategory: 'MAC安全',
    },
    {
      id: 'cmd-hsw-arp-security',
      name: '查看ARP安全',
      target: '华为交换机',
      command: 'display arp anti-attack',
      description: '查看ARP防攻击配置',
      os: 'VRP',
      brand: '华为',
      deviceType: '交换机',
      category: '入侵防范',
      subCategory: 'ARP安全',
    },
    {
      id: 'cmd-h3c-dhcp-snooping',
      name: '查看DHCP Snooping',
      target: 'H3C交换机',
      command: 'display dhcp snooping',
      description: '查看DHCP Snooping配置',
      os: 'Comware',
      brand: 'H3C',
      deviceType: '交换机',
      category: '入侵防范',
      subCategory: 'DHCP安全',
    },
    {
      id: 'cmd-h3c-802.1x',
      name: '查看802.1X认证',
      target: 'H3C交换机',
      command: 'display dot1x',
      description: '查看802.1X认证配置',
      os: 'Comware',
      brand: 'H3C',
      deviceType: '交换机',
      category: '身份鉴别',
      subCategory: '端口认证',
    },
    {
      id: 'cmd-csc-port-security',
      name: '查看端口安全',
      target: '思科交换机',
      command: 'show port-security',
      description: '查看端口安全配置',
      os: 'IOS',
      brand: '思科',
      deviceType: '交换机',
      category: '访问控制',
      subCategory: '端口安全',
    },
    {
      id: 'cmd-csc-dhcp-snooping',
      name: '查看DHCP Snooping',
      target: '思科交换机',
      command: 'show ip dhcp snooping',
      description: '查看DHCP Snooping配置',
      os: 'IOS',
      brand: '思科',
      deviceType: '交换机',
      category: '入侵防范',
      subCategory: 'DHCP安全',
    },
  ];
  commands.push(...switchSupplementCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 十八、防火墙补充 - IPS/AV/双机热备
  // ========================

  const fwSupplementCmds: SeedCommand[] = [
    {
      id: 'cmd-sf-ips',
      name: '查看IPS策略',
      target: '深信服防火墙',
      command: 'show ips all',
      description: '查看入侵防御系统策略',
      os: 'SANGFOR',
      brand: '深信服',
      deviceType: '防火墙',
      category: '入侵防范',
      subCategory: 'IPS策略',
    },
    {
      id: 'cmd-sf-av',
      name: '查看防病毒策略',
      target: '深信服防火墙',
      command: 'show av all',
      description: '查看防病毒扫描策略',
      os: 'SANGFOR',
      brand: '深信服',
      deviceType: '防火墙',
      category: '入侵防范',
      subCategory: 'AV策略',
    },
    {
      id: 'cmd-sf-ha',
      name: '查看双机热备',
      target: '深信服防火墙',
      command: 'show ha all',
      description: '查看高可用双机热备配置',
      os: 'SANGFOR',
      brand: '深信服',
      deviceType: '防火墙',
      category: '安全配置',
      subCategory: '高可用',
    },
    {
      id: 'cmd-hfw-ips',
      name: '查看IPS配置',
      target: '华为防火墙',
      command: 'display ips configuration',
      description: '查看IPS入侵防御配置',
      os: 'VRP',
      brand: '华为',
      deviceType: '防火墙',
      category: '入侵防范',
      subCategory: 'IPS策略',
    },
    {
      id: 'cmd-hfw-vpn-ipsec',
      name: '查看IPSec VPN',
      target: '华为防火墙',
      command: 'display ipsec sa',
      description: '查看IPSec VPN安全关联',
      os: 'VRP',
      brand: '华为',
      deviceType: '防火墙',
      category: '通信传输',
      subCategory: 'VPN',
    },
    {
      id: 'cmd-ts-ips',
      name: '查看IPS策略',
      target: '天融信防火墙',
      command: 'show ips policy',
      description: '查看入侵防御策略',
      os: 'TOPSEC',
      brand: '天融信',
      deviceType: '防火墙',
      category: '入侵防范',
      subCategory: 'IPS策略',
    },
    {
      id: 'cmd-ts-ha',
      name: '查看双机热备',
      target: '天融信防火墙',
      command: 'show ha',
      description: '查看双机热备状态',
      os: 'TOPSEC',
      brand: '天融信',
      deviceType: '防火墙',
      category: '安全配置',
      subCategory: '高可用',
    },
  ];
  commands.push(...fwSupplementCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 十九、Linux补充 - SELinux/cron/umask/SSH版本
  // ========================

  const linuxSupplementCmds: SeedCommand[] = [
    {
      id: 'cmd-linux-selinux',
      name: '查看SELinux状态',
      target: 'Linux服务器',
      command: 'getenforce',
      description: '查看SELinux强制访问控制状态',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '安全配置',
      subCategory: 'SELinux',
    },
    {
      id: 'cmd-linux-apparmor',
      name: '查看AppArmor状态',
      target: 'Linux服务器',
      command: 'aa-status',
      description: '查看AppArmor安全模块状态',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '安全配置',
      subCategory: 'AppArmor',
    },
    {
      id: 'cmd-linux-cron',
      name: '查看定时任务',
      target: 'Linux服务器',
      command: 'crontab -l && ls /etc/cron.d/',
      description: '查看用户和系统定时任务',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '安全审计',
      subCategory: '定时任务',
    },
    {
      id: 'cmd-linux-umask',
      name: '查看默认权限',
      target: 'Linux服务器',
      command: 'umask',
      description: '查看系统默认文件创建权限掩码',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '安全配置',
      subCategory: '权限配置',
    },
    {
      id: 'cmd-linux-ssh-version',
      name: '查看SSH协议版本',
      target: 'Linux服务器',
      command: 'ssh -V',
      description: '查看OpenSSH版本号',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '入侵防范',
      subCategory: '版本信息',
    },
    {
      id: 'cmd-linux-ssh-cipher',
      name: '查看SSH加密算法',
      target: 'Linux服务器',
      command: 'cat /etc/ssh/sshd_config | grep -E "Ciphers|MACs|KexAlgorithms"',
      description: '查看SSH加密算法配置',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '通信传输',
      subCategory: '加密传输',
    },
    {
      id: 'cmd-linux-tcp-wrap',
      name: '查看TCP Wrappers',
      target: 'Linux服务器',
      command: 'cat /etc/hosts.allow && cat /etc/hosts.deny',
      description: '查看TCP Wrappers访问控制',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '访问控制',
      subCategory: '网络访问',
    },
    {
      id: 'cmd-linux-pam-tally',
      name: '查看登录失败锁定',
      target: 'Linux服务器',
      command: 'pam_tally2 --user 用户名',
      description: '查看用户登录失败次数和锁定状态',
      os: 'Linux',
      brand: '通用',
      deviceType: '服务器',
      category: '身份鉴别',
      subCategory: '登录失败处理',
    },
  ];
  commands.push(...linuxSupplementCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 二十、Windows补充 - PowerShell/UAC/BitLocker/Defender
  // ========================

  const winSupplementCmds: SeedCommand[] = [
    {
      id: 'cmd-win-ps-policy',
      name: '查看PowerShell策略',
      target: 'Windows服务器',
      command: 'Get-ExecutionPolicy',
      description: '查看PowerShell脚本执行策略',
      os: 'Windows',
      brand: '微软',
      deviceType: '服务器',
      category: '安全配置',
      subCategory: 'PowerShell',
    },
    {
      id: 'cmd-win-uac',
      name: '查看UAC配置',
      target: 'Windows服务器',
      command: 'Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System | Select-Object EnableLUA',
      description: '查看用户账户控制UAC配置',
      os: 'Windows',
      brand: '微软',
      deviceType: '服务器',
      category: '访问控制',
      subCategory: 'UAC',
    },
    {
      id: 'cmd-win-bitlocker',
      name: '查看BitLocker状态',
      target: 'Windows服务器',
      command: 'Get-BitLockerVolume',
      description: '查看BitLocker磁盘加密状态',
      os: 'Windows',
      brand: '微软',
      deviceType: '服务器',
      category: '通信传输',
      subCategory: '数据加密',
    },
    {
      id: 'cmd-win-defender',
      name: '查看Defender状态',
      target: 'Windows服务器',
      command: 'Get-MpComputerStatus',
      description: '查看Windows Defender防病毒状态',
      os: 'Windows',
      brand: '微软',
      deviceType: '服务器',
      category: '入侵防范',
      subCategory: '防病毒',
    },
    {
      id: 'cmd-win-share',
      name: '查看共享权限',
      target: 'Windows服务器',
      command: 'Get-SmbShare | Get-SmbShareAccess',
      description: '查看SMB共享和权限配置',
      os: 'Windows',
      brand: '微软',
      deviceType: '服务器',
      category: '访问控制',
      subCategory: '共享权限',
    },
    {
      id: 'cmd-win-ldap',
      name: '查看LDAP签名',
      target: 'Windows服务器',
      command: 'Get-ItemProperty HKLM:\\SYSTEM\\CurrentControlSet\\Services\\NTDS\\Parameters | Select-Object LDAPServerIntegrity',
      description: '查看Active Directory LDAP签名配置',
      os: 'Windows',
      brand: '微软',
      deviceType: '服务器',
      category: '通信传输',
      subCategory: 'LDAP安全',
    },
    {
      id: 'cmd-win-smb',
      name: '查看SMB协议版本',
      target: 'Windows服务器',
      command: 'Get-SmbServerConfiguration | Select-Object EnableSMB1Protocol,EnableSMB2Protocol',
      description: '查看SMB协议版本配置',
      os: 'Windows',
      brand: '微软',
      deviceType: '服务器',
      category: '通信传输',
      subCategory: 'SMB安全',
    },
    {
      id: 'cmd-win-ntp',
      name: '查看NTP配置',
      target: 'Windows服务器',
      command: 'w32tm /query /configuration',
      description: '查看Windows时间同步配置',
      os: 'Windows',
      brand: '微软',
      deviceType: '服务器',
      category: '安全审计',
      subCategory: '时间同步',
    },
  ];
  commands.push(...winSupplementCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 二十一、Nginx/Tomcat补充 - server_tokens/AJP安全
  // ========================

  const middlewareSupplementCmds: SeedCommand[] = [
    {
      id: 'cmd-nginx-server-tokens',
      name: '查看版本隐藏',
      target: 'Nginx',
      command: "grep -E 'server_tokens|autoindex' /etc/nginx/nginx.conf",
      description: '查看Nginx版本号隐藏和目录列表配置',
      os: 'Linux',
      brand: 'Nginx',
      deviceType: '中间件',
      category: '安全配置',
      subCategory: '信息隐藏',
    },
    {
      id: 'cmd-nginx-access-control',
      name: '查看访问控制',
      target: 'Nginx',
      command: "grep -E 'allow|deny' /etc/nginx/conf.d/*.conf",
      description: '查看Nginx IP访问控制规则',
      os: 'Linux',
      brand: 'Nginx',
      deviceType: '中间件',
      category: '访问控制',
      subCategory: 'IP限制',
    },
    {
      id: 'cmd-nginx-cors',
      name: '查看CORS配置',
      target: 'Nginx',
      command: "grep -E 'Access-Control-Allow' /etc/nginx/conf.d/*.conf",
      description: '查看Nginx跨域资源共享配置',
      os: 'Linux',
      brand: 'Nginx',
      deviceType: '中间件',
      category: '安全配置',
      subCategory: 'CORS',
    },
    {
      id: 'cmd-tomcat-ajp',
      name: '查看AJP连接器',
      target: 'Tomcat',
      command: "grep -A10 'AJP' /usr/local/tomcat/conf/server.xml",
      description: '查看Tomcat AJP连接器安全配置',
      os: 'Linux',
      brand: 'Apache',
      deviceType: '中间件',
      category: '安全配置',
      subCategory: 'AJP安全',
    },
    {
      id: 'cmd-tomcat-shutdown',
      name: '查看关闭端口',
      target: 'Tomcat',
      command: "grep 'Server port' /usr/local/tomcat/conf/server.xml",
      description: '查看Tomcat关闭端口配置',
      os: 'Linux',
      brand: 'Apache',
      deviceType: '中间件',
      category: '安全配置',
      subCategory: '端口安全',
    },
    {
      id: 'cmd-tomcat-manager',
      name: '查看管理应用',
      target: 'Tomcat',
      command: "ls /usr/local/tomcat/webapps/",
      description: '查看Tomcat管理应用是否部署',
      os: 'Linux',
      brand: 'Apache',
      deviceType: '中间件',
      category: '访问控制',
      subCategory: '管理界面',
    },
    {
      id: 'cmd-apache-rewrite',
      name: '查看URL重写',
      target: 'Apache',
      command: "grep -E 'RewriteEngine|RewriteRule' /etc/httpd/conf.d/*.conf",
      description: '查看Apache URL重写规则',
      os: 'Linux',
      brand: 'Apache',
      deviceType: '中间件',
      category: '安全配置',
      subCategory: 'URL重写',
    },
    {
      id: 'cmd-apache-directory',
      name: '查看目录浏览',
      target: 'Apache',
      command: "grep -E 'Options.*Indexes' /etc/httpd/conf/httpd.conf",
      description: '查看Apache目录浏览配置',
      os: 'Linux',
      brand: 'Apache',
      deviceType: '中间件',
      category: '安全配置',
      subCategory: '目录安全',
    },
  ];
  commands.push(...middlewareSupplementCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  // ========================
  // 二十二、MySQL/Oracle补充 - 监听器安全/连接加密
  // ========================

  const dbSupplementCmds: SeedCommand[] = [
    {
      id: 'cmd-mysql-general-log',
      name: '查看通用日志',
      target: 'MySQL数据库',
      command: "SHOW VARIABLES LIKE 'general_log%';",
      description: '查看MySQL通用查询日志配置',
      os: 'MySQL',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '安全审计',
      subCategory: '日志配置',
    },
    {
      id: 'cmd-mysql-ssl-connection',
      name: '查看SSL连接',
      target: 'MySQL数据库',
      command: "SHOW STATUS LIKE 'Ssl_cipher';",
      description: '查看MySQL当前SSL加密连接状态',
      os: 'MySQL',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '通信传输',
      subCategory: '加密传输',
    },
    {
      id: 'cmd-mysql-max-connect',
      name: '查看连接限制',
      target: 'MySQL数据库',
      command: "SHOW VARIABLES LIKE 'max_connections';",
      description: '查看MySQL最大连接数限制',
      os: 'MySQL',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '入侵防范',
      subCategory: '连接控制',
    },
    {
      id: 'cmd-ora-listener',
      name: '查看监听器配置',
      target: 'Oracle数据库',
      command: 'lsnrctl status',
      description: '查看Oracle监听器配置和状态',
      os: 'Oracle',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '安全配置',
      subCategory: '监听器',
    },
    {
      id: 'cmd-ora-password-file',
      name: '查看密码文件',
      target: 'Oracle数据库',
      command: "SELECT value FROM v$parameter WHERE name='remote_login_passwordfile';",
      description: '查看远程登录密码文件配置',
      os: 'Oracle',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '身份鉴别',
      subCategory: '密码策略',
    },
    {
      id: 'cmd-ora-tde',
      name: '查看透明加密',
      target: 'Oracle数据库',
      command: "SELECT * FROM v$encrypted_tablespaces;",
      description: '查看Oracle透明数据加密配置',
      os: 'Oracle',
      brand: 'Oracle',
      deviceType: '数据库',
      category: '通信传输',
      subCategory: '数据加密',
    },
    {
      id: 'cmd-mssql-login-audit',
      name: '查看登录审计',
      target: 'SQL Server数据库',
      command: "SELECT name, is_checked FROM sys.server_audit_specifications;",
      description: '查看服务器登录审计规范',
      os: 'SQL Server',
      brand: '微软',
      deviceType: '数据库',
      category: '安全审计',
      subCategory: '审计配置',
    },
    {
      id: 'cmd-mssql-common-criteria',
      name: '查看合规配置',
      target: 'SQL Server数据库',
      command: "SELECT name, value_in_use FROM sys.configurations WHERE name LIKE '%common criteria%' OR name LIKE '%c2%';",
      description: '查看SQL Server C2审计和通用准则配置',
      os: 'SQL Server',
      brand: '微软',
      deviceType: '数据库',
      category: '安全审计',
      subCategory: '审计配置',
    },
  ];
  commands.push(...dbSupplementCmds.map(c => ({ ...c, createdAt: now, updatedAt: now })));

  return commands;
}
