import type { StandardItem } from '../types';

// 二级标准库种子文件 - 从S2A2G2.xlsx自动生成
// 生成时间: 2026-07-06T10:41:07.906Z
// 总项数: 190

export const STANDARD_GB_T_22239_2019_L2_ITEMS: StandardItem[] = [
  {
    id: 'gb22239-l2-secure_physical-1',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '物理位置选择',
    controlName: '物理位置选择',
    requirement: 'a）机房场地应选择在具有防震、防风和防雨等能力的建筑内；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 1,
  },
  {
    id: 'gb22239-l2-secure_physical-2',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '物理位置选择',
    controlName: '物理位置选择',
    requirement: 'b）机房场地应避免设在建筑物的顶层或地下室，否则应加强防水和防潮措施。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 2,
  },
  {
    id: 'gb22239-l2-secure_physical-3',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '物理访问控制',
    controlName: '物理访问控制',
    requirement: 'a）机房出入口应安排专人值守或配置电子门禁系统，控制、鉴别和记录进入的人员。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 3,
  },
  {
    id: 'gb22239-l2-secure_physical-4',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '防盗窃和防破坏',
    controlName: '防盗窃和防破坏',
    requirement: 'a）应将设备或主要部件进行固定，并设置明显的不易除去的标识；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 4,
  },
  {
    id: 'gb22239-l2-secure_physical-5',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '防盗窃和防破坏',
    controlName: '防盗窃和防破坏',
    requirement: 'b）应将通信线缆铺设在隐蔽安全处。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 5,
  },
  {
    id: 'gb22239-l2-secure_physical-6',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '防雷击',
    controlName: '防雷击',
    requirement: 'a）应将各类机柜、设施和设备等通过接地系统安全接地。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 6,
  },
  {
    id: 'gb22239-l2-secure_physical-7',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '防火',
    controlName: '防火',
    requirement: 'a）机房应设置火灾自动消防系统，能够自动检测火情、自动报警，并自动灭火；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 7,
  },
  {
    id: 'gb22239-l2-secure_physical-8',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '防火',
    controlName: '防火',
    requirement: 'b）机房及相关的工作房间和辅助房应采用具有耐火等级的建筑材料。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 8,
  },
  {
    id: 'gb22239-l2-secure_physical-9',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '防水和防潮',
    controlName: '防水和防潮',
    requirement: 'a）应采取措施防止雨水通过机房窗户、屋顶和墙壁渗透；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 9,
  },
  {
    id: 'gb22239-l2-secure_physical-10',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '防水和防潮',
    controlName: '防水和防潮',
    requirement: 'b）应采取措施防止机房内水蒸气结露和地下积水的转移与渗透。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 10,
  },
  {
    id: 'gb22239-l2-secure_physical-11',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '防静电',
    controlName: '防静电',
    requirement: 'a）应采用防静电地板或地面并采用必要的接地防静电措施。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 11,
  },
  {
    id: 'gb22239-l2-secure_physical-12',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '温湿度控制',
    controlName: '温湿度控制',
    requirement: 'a）应设置温湿度自动调节设施，使机房温湿度的变化在设备运行所允许的范围之内。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 12,
  },
  {
    id: 'gb22239-l2-secure_physical-13',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '电力供应',
    controlName: '电力供应',
    requirement: 'a）应在机房供电线路上配置稳压器和过电压防护设备；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 13,
  },
  {
    id: 'gb22239-l2-secure_physical-14',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '电力供应',
    controlName: '电力供应',
    requirement: 'b）应提供短期的备用电力供应，至少满足设备在断电情况下的正常运行要求。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 14,
  },
  {
    id: 'gb22239-l2-secure_physical-15',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '电磁防护',
    controlName: '电磁防护',
    requirement: 'a）电源线和通信线缆应隔离铺设，避免互相干扰。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 15,
  },
  {
    id: 'gb22239-l2-secure_physical-16',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '基础设施位置',
    controlName: '基础设施位置',
    requirement: 'a）应保证云计算基础设施位于中国境内。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'cloud',
    isHighRisk: 0,
    sortOrder: 16,
  },
  {
    id: 'gb22239-l2-secure_physical-17',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '无线接入点的物理位置',
    controlName: '无线接入点的物理位置',
    requirement: 'a）应为无线接入设备的安装选择合理位置，避免过度覆盖和电磁干扰。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'mobile',
    isHighRisk: 0,
    sortOrder: 17,
  },
  {
    id: 'gb22239-l2-secure_physical-18',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '感知节点设备物理防护',
    controlName: '感知节点设备物理防护',
    requirement: 'a）感知节点设备所处的物理环境应不对感知节点设备造成物理破坏，如挤压、强振动；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'iot',
    isHighRisk: 0,
    sortOrder: 18,
  },
  {
    id: 'gb22239-l2-secure_physical-19',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '感知节点设备物理防护',
    controlName: '感知节点设备物理防护',
    requirement: 'b）感知节点设备在工作状态所处物理环境应能正确反映环境状态（如温湿度传感器不能安装在阳光直射区域）。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'iot',
    isHighRisk: 0,
    sortOrder: 19,
  },
  {
    id: 'gb22239-l2-secure_physical-20',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '室外控制设备物理防护',
    controlName: '室外控制设备物理防护',
    requirement: 'a）室外控制设备应放置于采用铁板或其他防火材料制作的箱体或装置中并紧固；箱体或装置具有透风、散热、防盗、防雨和防火能力等；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'industrial',
    isHighRisk: 0,
    sortOrder: 20,
  },
  {
    id: 'gb22239-l2-secure_physical-21',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '室外控制设备物理防护',
    controlName: '室外控制设备物理防护',
    requirement: 'b）室外控制设备放置应远离强电磁干扰、强热源等环境，如无法避免应及时做好应急处置及检修，保证设备正常运行。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'industrial',
    isHighRisk: 0,
    sortOrder: 21,
  },
  {
    id: 'gb22239-l2-secure_physical-22',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_physical',
    controlPoint: '大数据平台',
    controlName: '大数据平台',
    requirement: 'a）应保证承载大数据存储、处理和分析的设备机房位于中国境内。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'bigdata',
    isHighRisk: 0,
    sortOrder: 22,
  },
  {
    id: 'gb22239-l2-secure_communication-23',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_communication',
    controlPoint: '网络架构',
    controlName: '网络架构',
    requirement: 'a）应划分不同的网络区域，并按照方便管理和控制的原则为各网络区域分配地址；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 23,
  },
  {
    id: 'gb22239-l2-secure_communication-24',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_communication',
    controlPoint: '网络架构',
    controlName: '网络架构',
    requirement: 'b）应避免将重要网络区域部署在边界处，重要网络区域与其他网络区域之间应采取可靠的技术隔离手段。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 24,
  },
  {
    id: 'gb22239-l2-secure_communication-25',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_communication',
    controlPoint: '通信传输',
    controlName: '通信传输',
    requirement: 'a）应采用校验技术保证通信过程中数据的完整性。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 25,
  },
  {
    id: 'gb22239-l2-secure_communication-26',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_communication',
    controlPoint: '可信验证',
    controlName: '可信验证',
    requirement: 'a）可基于可信根对通信设备的系统引导程序、系统程序、重要配置参数和通信应用程序等进行可信验证，并在检测到其可信性受到破坏后进行报警，并将验证结果形成审计记录送至安全管理中心。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 26,
  },
  {
    id: 'gb22239-l2-secure_communication-27',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_communication',
    controlPoint: '网络架构',
    controlName: '网络架构',
    requirement: 'a）应保证云计算平台不承载高于其安全保护等级的业务应用系统；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'cloud',
    isHighRisk: 0,
    sortOrder: 27,
  },
  {
    id: 'gb22239-l2-secure_communication-28',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_communication',
    controlPoint: '网络架构',
    controlName: '网络架构',
    requirement: 'b）应实现不同云服务客户虚拟网络之间的隔离；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'cloud',
    isHighRisk: 0,
    sortOrder: 28,
  },
  {
    id: 'gb22239-l2-secure_communication-29',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_communication',
    controlPoint: '网络架构',
    controlName: '网络架构',
    requirement: 'c）应具有根据云服务客户业务需求提供通信传输、边界防护、入侵防范等安全机制的能力。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'cloud',
    isHighRisk: 0,
    sortOrder: 29,
  },
  {
    id: 'gb22239-l2-secure_communication-30',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_communication',
    controlPoint: '网络架构',
    controlName: '网络架构',
    requirement: 'a）工业控制系统与企业其他系统之间应划分为两个区域，区域间应采用技术隔离手段；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'industrial',
    isHighRisk: 0,
    sortOrder: 30,
  },
  {
    id: 'gb22239-l2-secure_communication-31',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_communication',
    controlPoint: '网络架构',
    controlName: '网络架构',
    requirement: 'b）工业控制系统内部应根据业务特点划分为不同的安全域，安全域之间应采用技术隔离手段；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'industrial',
    isHighRisk: 0,
    sortOrder: 31,
  },
  {
    id: 'gb22239-l2-secure_communication-32',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_communication',
    controlPoint: '网络架构',
    controlName: '网络架构',
    requirement: 'c）涉及实时控制和数据传输的工业控制系统，应使用独立的网络设备组网，在物理层面上实现与其它数据网及外部公共信息网的安全隔离。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'industrial',
    isHighRisk: 0,
    sortOrder: 32,
  },
  {
    id: 'gb22239-l2-secure_communication-33',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_communication',
    controlPoint: '通信传输',
    controlName: '通信传输',
    requirement: 'a）在工业控制系统内使用广域网进行控制指令或相关数据交换的应采用加密认证技术手段实现身份认证、访问控制和数据加密传输。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'industrial',
    isHighRisk: 0,
    sortOrder: 33,
  },
  {
    id: 'gb22239-l2-secure_communication-34',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_communication',
    controlPoint: '大数据平台',
    controlName: '大数据平台',
    requirement: 'a）应保证大数据平台不承载高于其安全保护等级的大数据应用和大数据资源。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'bigdata',
    isHighRisk: 0,
    sortOrder: 34,
  },
  {
    id: 'gb22239-l2-secure_boundary-35',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '边界防护',
    controlName: '边界防护',
    requirement: 'a）应保证跨越边界的访问和数据流通过边界设备提供的受控接口进行通信。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 35,
  },
  {
    id: 'gb22239-l2-secure_boundary-36',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '访问控制',
    controlName: '访问控制',
    requirement: 'a）应在网络边界或区域之间根据访问控制策略设置访问控制规则，默认情况下除允许通信外受控接口拒绝所有通信；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 36,
  },
  {
    id: 'gb22239-l2-secure_boundary-37',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '访问控制',
    controlName: '访问控制',
    requirement: 'b）应删除多余或无效的访问控制规则，优化访问控制列表，并保证访问控制规则数量最小化；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 37,
  },
  {
    id: 'gb22239-l2-secure_boundary-38',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '访问控制',
    controlName: '访问控制',
    requirement: 'c）应对源地址、目的地址、源端口、目的端口和协议等进行检查，以允许/拒绝数据包进出；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 38,
  },
  {
    id: 'gb22239-l2-secure_boundary-39',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '访问控制',
    controlName: '访问控制',
    requirement: 'd）应能根据会话状态信息为进出数据流提供明确的允许/拒绝访问的能力。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 39,
  },
  {
    id: 'gb22239-l2-secure_boundary-40',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '入侵防范',
    controlName: '入侵防范',
    requirement: 'a）应在关键网络节点处监视网络攻击行为。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 40,
  },
  {
    id: 'gb22239-l2-secure_boundary-41',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '恶意代码防范',
    controlName: '恶意代码防范',
    requirement: 'a）应在关键网络节点处对恶意代码进行检测和清除，并维护恶意代码防护机制的升级和更新。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 41,
  },
  {
    id: 'gb22239-l2-secure_boundary-42',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '安全审计',
    controlName: '安全审计',
    requirement: 'a）应在网络边界、重要网络节点进行安全审计，审计覆盖到每个用户，对重要的用户行为和重要安全事件进行审计；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 42,
  },
  {
    id: 'gb22239-l2-secure_boundary-43',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '安全审计',
    controlName: '安全审计',
    requirement: 'b）审计记录应包括事件的日期和时间、用户、事件类型、事件是否成功及其他与审计相关的信息；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 43,
  },
  {
    id: 'gb22239-l2-secure_boundary-44',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '安全审计',
    controlName: '安全审计',
    requirement: 'c）应对审计记录进行保护，定期备份，避免受到未预期的删除、修改或覆盖等。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 44,
  },
  {
    id: 'gb22239-l2-secure_boundary-45',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '可信验证',
    controlName: '可信验证',
    requirement: 'a）可基于可信根对边界设备的系统引导程序、系统程序、重要配置参数和边界防护应用程序等进行可信验证，并在检测到其可信性受到破坏后进行报警，并将验证结果形成审计记录送至安全管理中心。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 45,
  },
  {
    id: 'gb22239-l2-secure_boundary-46',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '访问控制',
    controlName: '访问控制',
    requirement: 'a）应在虚拟化网络边界部署访问控制机制，并设置访问控制规则；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'cloud',
    isHighRisk: 0,
    sortOrder: 46,
  },
  {
    id: 'gb22239-l2-secure_boundary-47',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '访问控制',
    controlName: '访问控制',
    requirement: 'b）应在不同等级的网络区域边界部署访问控制机制，设置访问控制规则。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'cloud',
    isHighRisk: 0,
    sortOrder: 47,
  },
  {
    id: 'gb22239-l2-secure_boundary-48',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '入侵防范',
    controlName: '入侵防范',
    requirement: 'a）应能检测到云服务客户发起的网络攻击行为，并能记录攻击类型、攻击时间、攻击流量等；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'cloud',
    isHighRisk: 0,
    sortOrder: 48,
  },
  {
    id: 'gb22239-l2-secure_boundary-49',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '入侵防范',
    controlName: '入侵防范',
    requirement: 'b）应能检测到对虚拟网络节点的网络攻击行为，并能记录攻击类型、攻击时间、攻击流量等；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'cloud',
    isHighRisk: 0,
    sortOrder: 49,
  },
  {
    id: 'gb22239-l2-secure_boundary-50',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '入侵防范',
    controlName: '入侵防范',
    requirement: 'c）应能检测到虚拟机与宿主机、虚拟机与虚拟机之间的异常流量。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'cloud',
    isHighRisk: 0,
    sortOrder: 50,
  },
  {
    id: 'gb22239-l2-secure_boundary-51',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '安全审计',
    controlName: '安全审计',
    requirement: 'a）应对云服务商和云服务客户在远程管理时执行的特权命令进行审计，至少包括虚拟机删除、虚拟机重启；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'cloud',
    isHighRisk: 0,
    sortOrder: 51,
  },
  {
    id: 'gb22239-l2-secure_boundary-52',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '安全审计',
    controlName: '安全审计',
    requirement: 'b）应保证云服务商对云服务客户系统和数据的操作可被云服务客户审计。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'cloud',
    isHighRisk: 0,
    sortOrder: 52,
  },
  {
    id: 'gb22239-l2-secure_boundary-53',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '边界防护',
    controlName: '边界防护',
    requirement: 'a）应保证有线网络与无线网络边界之间的访问和数据流通过无线接入网关设备。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'mobile',
    isHighRisk: 0,
    sortOrder: 53,
  },
  {
    id: 'gb22239-l2-secure_boundary-54',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '访问控制',
    controlName: '访问控制',
    requirement: 'a）无线接入设备应开启接入认证功能，并且禁止使用WEP方式进行认证，如使用口令，长度不小于8位字符；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'mobile',
    isHighRisk: 0,
    sortOrder: 54,
  },
  {
    id: 'gb22239-l2-secure_boundary-55',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '入侵防范',
    controlName: '入侵防范',
    requirement: 'a）应能够检测到非授权无线接入设备和非授权移动终端的接入行为；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'mobile',
    isHighRisk: 0,
    sortOrder: 55,
  },
  {
    id: 'gb22239-l2-secure_boundary-56',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '入侵防范',
    controlName: '入侵防范',
    requirement: 'b）应能够检测到针对无线接入设备的网络扫描、DDoS攻击、密钥破解、中间人攻击和欺骗攻击等行为；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'mobile',
    isHighRisk: 0,
    sortOrder: 56,
  },
  {
    id: 'gb22239-l2-secure_boundary-57',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '入侵防范',
    controlName: '入侵防范',
    requirement: 'c）应能够检测到无线接入设备的SSID 广播、WPS等高风险功能的开启状态；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'mobile',
    isHighRisk: 0,
    sortOrder: 57,
  },
  {
    id: 'gb22239-l2-secure_boundary-58',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '入侵防范',
    controlName: '入侵防范',
    requirement: 'd）应禁用无线接入设备和无线接入网关存在风险的功能，如：SSID广播、WEP认证等；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'mobile',
    isHighRisk: 0,
    sortOrder: 58,
  },
  {
    id: 'gb22239-l2-secure_boundary-59',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '入侵防范',
    controlName: '入侵防范',
    requirement: 'e）应禁止多个AP使用同一个认证密钥。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'mobile',
    isHighRisk: 0,
    sortOrder: 59,
  },
  {
    id: 'gb22239-l2-secure_boundary-60',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '接入控制',
    controlName: '接入控制',
    requirement: 'a）应保证只有授权的感知节点可以接入。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'iot',
    isHighRisk: 0,
    sortOrder: 60,
  },
  {
    id: 'gb22239-l2-secure_boundary-61',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '入侵防范',
    controlName: '入侵防范',
    requirement: 'a）应能够限制与感知节点通信的目标地址，以避免对陌生地址的攻击行为；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'iot',
    isHighRisk: 0,
    sortOrder: 61,
  },
  {
    id: 'gb22239-l2-secure_boundary-62',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '入侵防范',
    controlName: '入侵防范',
    requirement: 'b）应能够限制与网关节点通信的目标地址，以避免对陌生地址的攻击行为。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'iot',
    isHighRisk: 0,
    sortOrder: 62,
  },
  {
    id: 'gb22239-l2-secure_boundary-63',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '访问控制',
    controlName: '访问控制',
    requirement: 'a）应在工业控制系统与企业其他系统之间部署访问控制设备，配置访问控制策略，禁止任何穿越区域边界的E-Mail、Web、Telnet、Rlogin、FTP等通用网络服务；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'industrial',
    isHighRisk: 0,
    sortOrder: 63,
  },
  {
    id: 'gb22239-l2-secure_boundary-64',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '访问控制',
    controlName: '访问控制',
    requirement: 'b）应在工业控制系统内安全域和安全域之间的边界防护机制失效时，及时进行报警。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'industrial',
    isHighRisk: 0,
    sortOrder: 64,
  },
  {
    id: 'gb22239-l2-secure_boundary-65',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '拨号使用控制',
    controlName: '拨号使用控制',
    requirement: 'a）工业控制系统确需使用拨号访问服务的，应限制具有拨号访问权限的用户数量，并采取用户身份鉴别和访问控制等措施。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'industrial',
    isHighRisk: 0,
    sortOrder: 65,
  },
  {
    id: 'gb22239-l2-secure_boundary-66',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '无线使用控制',
    controlName: '无线使用控制',
    requirement: 'a）应对所有参与无线通信的用户（人员、软件进程或者设备）提供唯一性标识和鉴别；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'industrial',
    isHighRisk: 0,
    sortOrder: 66,
  },
  {
    id: 'gb22239-l2-secure_boundary-67',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_boundary',
    controlPoint: '无线使用控制',
    controlName: '无线使用控制',
    requirement: 'b）应对所有参与无线通信的用户（人员、软件进程或者设备）进行授权以及执行使用进行限制。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'industrial',
    isHighRisk: 0,
    sortOrder: 67,
  },
  {
    id: 'gb22239-l2-secure_computing-68',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '身份鉴别',
    controlName: '身份鉴别',
    requirement: 'a）应对登录的用户进行身份标识和鉴别，身份标识具有唯一性，身份鉴别信息具有复杂度要求并定期更换；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 68,
  },
  {
    id: 'gb22239-l2-secure_computing-69',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '身份鉴别',
    controlName: '身份鉴别',
    requirement: 'b）应具有登录失败处理功能，应配置并启用结束会话、限制非法登录次数和当登录连接超时自动退出等相关措施；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 69,
  },
  {
    id: 'gb22239-l2-secure_computing-70',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '身份鉴别',
    controlName: '身份鉴别',
    requirement: 'c）当进行远程管理时，应采取必要措施防止鉴别信息在网络传输过程中被窃听。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 70,
  },
  {
    id: 'gb22239-l2-secure_computing-71',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '访问控制',
    controlName: '访问控制',
    requirement: 'a）应对登录的用户分配账户和权限；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 71,
  },
  {
    id: 'gb22239-l2-secure_computing-72',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '访问控制',
    controlName: '访问控制',
    requirement: 'b）应重命名或删除默认账户，修改默认账户的默认口令；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 72,
  },
  {
    id: 'gb22239-l2-secure_computing-73',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '访问控制',
    controlName: '访问控制',
    requirement: 'c）应及时删除或停用多余的、过期的账户，避免共享账户的存在；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 73,
  },
  {
    id: 'gb22239-l2-secure_computing-74',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '访问控制',
    controlName: '访问控制',
    requirement: 'd）应授予管理用户所需的最小权限，实现管理用户的权限分离。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 74,
  },
  {
    id: 'gb22239-l2-secure_computing-75',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '安全审计',
    controlName: '安全审计',
    requirement: 'a）应启用安全审计功能，审计覆盖到每个用户，对重要的用户行为和重要安全事件进行审计；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 75,
  },
  {
    id: 'gb22239-l2-secure_computing-76',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '安全审计',
    controlName: '安全审计',
    requirement: 'b）审计记录应包括事件的日期和时间、用户、事件类型、事件是否成功及其他与审计相关的信息；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 76,
  },
  {
    id: 'gb22239-l2-secure_computing-77',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '安全审计',
    controlName: '安全审计',
    requirement: 'c）应对审计记录进行保护，定期备份，避免受到未预期的删除、修改或覆盖等。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 77,
  },
  {
    id: 'gb22239-l2-secure_computing-78',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '入侵防范',
    controlName: '入侵防范',
    requirement: 'a）应遵循最小安装的原则，仅安装需要的组件和应用程序；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 78,
  },
  {
    id: 'gb22239-l2-secure_computing-79',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '入侵防范',
    controlName: '入侵防范',
    requirement: 'b）应关闭不需要的系统服务、默认共享和高危端口；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 79,
  },
  {
    id: 'gb22239-l2-secure_computing-80',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '入侵防范',
    controlName: '入侵防范',
    requirement: 'c）应通过设定终端接入方式或网络地址范围对通过网络进行管理的管理终端进行限制；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 80,
  },
  {
    id: 'gb22239-l2-secure_computing-81',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '入侵防范',
    controlName: '入侵防范',
    requirement: 'd）应提供数据有效性检验功能，保证通过人机接口输入或通过通信接口输入的内容符合系统设定要求；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 81,
  },
  {
    id: 'gb22239-l2-secure_computing-82',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '入侵防范',
    controlName: '入侵防范',
    requirement: 'e）应能发现可能存在的已知漏洞，并在经过充分测试评估后，及时修补漏洞。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 82,
  },
  {
    id: 'gb22239-l2-secure_computing-83',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '恶意代码防范',
    controlName: '恶意代码防范',
    requirement: 'a）应安装防恶意代码软件或配置具有相应功能的软件，并定期进行升级和更新防恶意代码库。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 83,
  },
  {
    id: 'gb22239-l2-secure_computing-84',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '可信验证',
    controlName: '可信验证',
    requirement: 'a）可基于可信根对计算设备的系统引导程序、系统程序、重要配置参数和应用程序等进行可信验证，并在检测到其可信性受到破坏后进行报警，并将验证结果形成审计记录送至安全管理中心。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 84,
  },
  {
    id: 'gb22239-l2-secure_computing-85',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '数据完整性',
    controlName: '数据完整性',
    requirement: 'a）应采用校验技术保证重要数据在传输过程中的完整性。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 85,
  },
  {
    id: 'gb22239-l2-secure_computing-86',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '数据备份恢复',
    controlName: '数据备份恢复',
    requirement: 'a）应提供重要数据的本地数据备份与恢复功能；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 86,
  },
  {
    id: 'gb22239-l2-secure_computing-87',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '数据备份恢复',
    controlName: '数据备份恢复',
    requirement: 'b）应提供异地数据备份功能，利用通信网络将重要数据定时批量传送至备用场地。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 87,
  },
  {
    id: 'gb22239-l2-secure_computing-88',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '剩余信息保护',
    controlName: '剩余信息保护',
    requirement: 'a）应保证鉴别信息所在的存储空间被释放或重新分配前得到完全清除。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 88,
  },
  {
    id: 'gb22239-l2-secure_computing-89',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '个人信息保护',
    controlName: '个人信息保护',
    requirement: 'a）应仅采集和保存业务必需的用户个人信息；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 89,
  },
  {
    id: 'gb22239-l2-secure_computing-90',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_computing',
    controlPoint: '个人信息保护',
    controlName: '个人信息保护',
    requirement: 'b）应禁止未授权访问和非法使用用户个人信息。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 90,
  },
  {
    id: 'gb22239-l2-secure_management-91',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_management',
    controlPoint: '系统管理',
    controlName: '系统管理',
    requirement: 'a）应对系统管理员进行身份鉴别，只允许其通过特定的命令或操作界面进行系统管理操作，并对这些操作进行审计；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 91,
  },
  {
    id: 'gb22239-l2-secure_management-92',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_management',
    controlPoint: '系统管理',
    controlName: '系统管理',
    requirement: 'b）应通过系统管理员对系统的资源和运行进行配置、控制和管理，包括用户身份、系统资源配置、系统加载和启动、系统运行的异常处理、数据和设备的备份与恢复等。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 92,
  },
  {
    id: 'gb22239-l2-secure_management-93',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_management',
    controlPoint: '审计管理',
    controlName: '审计管理',
    requirement: 'a）应对审计管理员进行身份鉴别，只允许其通过特定的命令或操作界面进行安全审计操作，并对这些操作进行审计；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 93,
  },
  {
    id: 'gb22239-l2-secure_management-94',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'secure_management',
    controlPoint: '审计管理',
    controlName: '审计管理',
    requirement: 'b）应通过审计管理员对审计记录进行分析，并根据分析结果进行处理，包括根据安全审计策略对审计记录进行存储、管理和查询等。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 94,
  },
  {
    id: 'gb22239-l2-security_management-95',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_management',
    controlPoint: '安全策略',
    controlName: '安全策略',
    requirement: 'a）应制定网络安全工作的总体方针和安全策略，阐明机构安全工作的总体目标、范围、原则和安全框架等。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 95,
  },
  {
    id: 'gb22239-l2-security_management-96',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_management',
    controlPoint: '管理制度',
    controlName: '管理制度',
    requirement: 'a）应对安全管理活动中的主要管理内容建立安全管理制度；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 96,
  },
  {
    id: 'gb22239-l2-security_management-97',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_management',
    controlPoint: '管理制度',
    controlName: '管理制度',
    requirement: 'b）应对管理人员或操作人员执行的日常管理操作建立操作规程。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 97,
  },
  {
    id: 'gb22239-l2-security_management-98',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_management',
    controlPoint: '制定和发布',
    controlName: '制定和发布',
    requirement: 'a）应指定或授权专门的部门或人员负责安全管理制度的制定；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 98,
  },
  {
    id: 'gb22239-l2-security_management-99',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_management',
    controlPoint: '制定和发布',
    controlName: '制定和发布',
    requirement: 'b）安全管理制度应通过正式、有效的方式发布，并进行版本控制。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 99,
  },
  {
    id: 'gb22239-l2-security_management-100',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_management',
    controlPoint: '评审和修订',
    controlName: '评审和修订',
    requirement: 'a）应定期对安全管理制度的合理性和适用性进行论证和审定，对存在不足或需要改进的安全管理制度进行修订。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 100,
  },
  {
    id: 'gb22239-l2-security_organization-101',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_organization',
    controlPoint: '岗位设置',
    controlName: '岗位设置',
    requirement: 'a）应设立网络安全管理工作的职能部门，设立安全主管、安全管理各个方面的负责人岗位，并定义各负责人的职责；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 101,
  },
  {
    id: 'gb22239-l2-security_organization-102',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_organization',
    controlPoint: '岗位设置',
    controlName: '岗位设置',
    requirement: 'b）应设立系统管理员、审计管理员和安全管理员等岗位，并定义部门及各个工作岗位的职责。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 102,
  },
  {
    id: 'gb22239-l2-security_organization-103',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_organization',
    controlPoint: '人员配备',
    controlName: '人员配备',
    requirement: 'a）应配备一定数量的系统管理员、审计管理员和安全管理员等。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 103,
  },
  {
    id: 'gb22239-l2-security_organization-104',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_organization',
    controlPoint: '授权和审批',
    controlName: '授权和审批',
    requirement: 'a）应根据各个部门和岗位的职责明确授权审批事项、审批部门和批准人等；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 104,
  },
  {
    id: 'gb22239-l2-security_organization-105',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_organization',
    controlPoint: '授权和审批',
    controlName: '授权和审批',
    requirement: 'b）应针对系统变更、重要操作、物理访问和系统接入等事项执行审批过程。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 105,
  },
  {
    id: 'gb22239-l2-security_organization-106',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_organization',
    controlPoint: '沟通和合作',
    controlName: '沟通和合作',
    requirement: 'a）应加强各类管理人员、组织内部机构和网络安全管理部门之间的合作与沟通，定期召开协调会议，共同协作处理网络安全问题；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 106,
  },
  {
    id: 'gb22239-l2-security_organization-107',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_organization',
    controlPoint: '沟通和合作',
    controlName: '沟通和合作',
    requirement: 'b）应加强与网络安全职能部门、各类供应商、业界专家及安全组织的合作与沟通；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 107,
  },
  {
    id: 'gb22239-l2-security_organization-108',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_organization',
    controlPoint: '沟通和合作',
    controlName: '沟通和合作',
    requirement: 'c）应建立外联单位联系列表，包括外联单位名称、合作内容、联系人和联系方式等信息。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 108,
  },
  {
    id: 'gb22239-l2-security_organization-109',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_organization',
    controlPoint: '审核和检查',
    controlName: '审核和检查',
    requirement: 'a）应定期进行常规安全检查，检查内容包括系统日常运行、系统漏洞和数据备份等情况。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 109,
  },
  {
    id: 'gb22239-l2-security_personnel-110',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_personnel',
    controlPoint: '人员录用',
    controlName: '人员录用',
    requirement: 'a）应指定或授权专门的部门或人员负责人员录用；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 110,
  },
  {
    id: 'gb22239-l2-security_personnel-111',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_personnel',
    controlPoint: '人员录用',
    controlName: '人员录用',
    requirement: 'b）应对被录用人员的身份、安全背景、专业资格或资质等进行审查。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 111,
  },
  {
    id: 'gb22239-l2-security_personnel-112',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_personnel',
    controlPoint: '人员离岗',
    controlName: '人员离岗',
    requirement: 'a）应及时终止离岗人员的所有访问权限，取回各种身份证件、钥匙、徽章等以及机构提供的软硬件设备。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 112,
  },
  {
    id: 'gb22239-l2-security_personnel-113',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_personnel',
    controlPoint: '安全意识教育和培训',
    controlName: '安全意识教育和培训',
    requirement: 'a）应对各类人员进行安全意识教育和岗位技能培训，并告知相关的安全责任和惩戒措施。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 113,
  },
  {
    id: 'gb22239-l2-security_personnel-114',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_personnel',
    controlPoint: '外部人员访问管理',
    controlName: '外部人员访问管理',
    requirement: 'a）应在外部人员物理访问受控区域前先提出书面申请，批准后由专人全程陪同，并登记备案；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 114,
  },
  {
    id: 'gb22239-l2-security_personnel-115',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_personnel',
    controlPoint: '外部人员访问管理',
    controlName: '外部人员访问管理',
    requirement: 'b）应在外部人员接入受控网络访问系统前先提出书面申请，批准后由专人开设账户、分配权限，并登记备案；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 115,
  },
  {
    id: 'gb22239-l2-security_personnel-116',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_personnel',
    controlPoint: '外部人员访问管理',
    controlName: '外部人员访问管理',
    requirement: 'c）外部人员离场后应及时清除其所有的访问权限。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 116,
  },
  {
    id: 'gb22239-l2-security_construction-117',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '定级和备案',
    controlName: '定级和备案',
    requirement: 'a）应以书面的形式说明保护对象的安全保护等级及确定等级的方法和理由；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 117,
  },
  {
    id: 'gb22239-l2-security_construction-118',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '定级和备案',
    controlName: '定级和备案',
    requirement: 'b）应组织相关部门和有关安全技术专家对定级结果的合理性和正确性进行论证和审定；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 118,
  },
  {
    id: 'gb22239-l2-security_construction-119',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '定级和备案',
    controlName: '定级和备案',
    requirement: 'c）应保证定级结果经过相关部门的批准；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 119,
  },
  {
    id: 'gb22239-l2-security_construction-120',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '定级和备案',
    controlName: '定级和备案',
    requirement: 'd）应将备案材料报主管部门和相应公安机关备案。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 120,
  },
  {
    id: 'gb22239-l2-security_construction-121',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '安全方案设计',
    controlName: '安全方案设计',
    requirement: 'a）应根据安全保护等级选择基本安全措施，依据风险分析的结果补充和调整安全措施；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 121,
  },
  {
    id: 'gb22239-l2-security_construction-122',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '安全方案设计',
    controlName: '安全方案设计',
    requirement: 'b）应根据保护对象的安全保护等级进行安全方案设计；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 122,
  },
  {
    id: 'gb22239-l2-security_construction-123',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '安全方案设计',
    controlName: '安全方案设计',
    requirement: 'c）应组织相关部门和有关安全专家对安全方案的合理性和正确性进行论证和审定，经过批准后才能正式实施。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 123,
  },
  {
    id: 'gb22239-l2-security_construction-124',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '产品采购和使用',
    controlName: '产品采购和使用',
    requirement: 'a）应确保网络安全产品采购和使用符合国家的有关规定；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 124,
  },
  {
    id: 'gb22239-l2-security_construction-125',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '产品采购和使用',
    controlName: '产品采购和使用',
    requirement: 'b）应确保密码产品与服务的采购和使用符合国家密码管理主管部门的要求。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 125,
  },
  {
    id: 'gb22239-l2-security_construction-126',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '自行软件开发',
    controlName: '自行软件开发',
    requirement: 'a）应将开发环境与实际运行环境物理分开，测试数据和测试结果受到控制；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 126,
  },
  {
    id: 'gb22239-l2-security_construction-127',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '自行软件开发',
    controlName: '自行软件开发',
    requirement: 'b）应在软件开发过程中对安全性进行测试，在软件安装前对可能存在的恶意代码进行检测。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 127,
  },
  {
    id: 'gb22239-l2-security_construction-128',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '外包软件开发',
    controlName: '外包软件开发',
    requirement: 'a）应在软件交付前检测其中可能存在的恶意代码；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 128,
  },
  {
    id: 'gb22239-l2-security_construction-129',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '外包软件开发',
    controlName: '外包软件开发',
    requirement: 'b）应保证开发单位提供软件设计文档和使用指南。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 129,
  },
  {
    id: 'gb22239-l2-security_construction-130',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '工程实施',
    controlName: '工程实施',
    requirement: 'a）应指定或授权专门的部门或人员负责工程实施过程的管理；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 130,
  },
  {
    id: 'gb22239-l2-security_construction-131',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '工程实施',
    controlName: '工程实施',
    requirement: 'b）应制定安全工程实施方案控制工程实施过程。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 131,
  },
  {
    id: 'gb22239-l2-security_construction-132',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '测试验收',
    controlName: '测试验收',
    requirement: 'a）应制订测试验收方案，并依据测试验收方案实施测试验收，形成测试验收报告；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 132,
  },
  {
    id: 'gb22239-l2-security_construction-133',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '测试验收',
    controlName: '测试验收',
    requirement: 'b）应进行上线前的安全性测试，并出具安全测试报告。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 133,
  },
  {
    id: 'gb22239-l2-security_construction-134',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '系统交付',
    controlName: '系统交付',
    requirement: 'a）应制定交付清单，并根据交付清单对所交接的设备、软件和文档等进行清点；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 134,
  },
  {
    id: 'gb22239-l2-security_construction-135',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '系统交付',
    controlName: '系统交付',
    requirement: 'b）应对负责运行维护的技术人员进行相应的技能培训；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 135,
  },
  {
    id: 'gb22239-l2-security_construction-136',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '系统交付',
    controlName: '系统交付',
    requirement: 'c）应提供建设过程文档和运行维护文档。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 136,
  },
  {
    id: 'gb22239-l2-security_construction-137',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '等级测评',
    controlName: '等级测评',
    requirement: 'a）应定期进行等级测评，发现不符合相应等级保护标准要求的及时整改；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 137,
  },
  {
    id: 'gb22239-l2-security_construction-138',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '等级测评',
    controlName: '等级测评',
    requirement: 'b）应在发生重大变更或级别发生变化时进行等级测评；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 138,
  },
  {
    id: 'gb22239-l2-security_construction-139',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '等级测评',
    controlName: '等级测评',
    requirement: 'c）应确保测评机构的选择符合国家有关规定。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 139,
  },
  {
    id: 'gb22239-l2-security_construction-140',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '服务供应商选择',
    controlName: '服务供应商选择',
    requirement: 'a）应确保服务供应商的选择符合国家的有关规定；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 140,
  },
  {
    id: 'gb22239-l2-security_construction-141',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '服务供应商选择',
    controlName: '服务供应商选择',
    requirement: 'b）应与选定的服务供应商签订相关协议，明确整个服务供应链各方需履行的网络安全相关义务。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 141,
  },
  {
    id: 'gb22239-l2-security_construction-142',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '云服务商选择',
    controlName: '云服务商选择',
    requirement: 'a）应选择安全合规的云服务商，其所提供的云计算平台应为其所承载的业务应用系统提供相应等级的安全保护能力；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'cloud',
    isHighRisk: 0,
    sortOrder: 142,
  },
  {
    id: 'gb22239-l2-security_construction-143',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '云服务商选择',
    controlName: '云服务商选择',
    requirement: 'b）应在服务水平协议中规定云服务的各项服务内容和具体技术指标；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'cloud',
    isHighRisk: 0,
    sortOrder: 143,
  },
  {
    id: 'gb22239-l2-security_construction-144',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '云服务商选择',
    controlName: '云服务商选择',
    requirement: 'c）应在服务水平协议中规定云服务商的权限与责任，包括管理范围、职责划分、访问授权、隐私保护、行为准则、违约责任等；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'cloud',
    isHighRisk: 0,
    sortOrder: 144,
  },
  {
    id: 'gb22239-l2-security_construction-145',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '云服务商选择',
    controlName: '云服务商选择',
    requirement: 'd）应在服务水平协议中规定服务合约到期时，完整提供云服务客户数据，并承诺相关数据在云计算平台上清除。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'cloud',
    isHighRisk: 0,
    sortOrder: 145,
  },
  {
    id: 'gb22239-l2-security_construction-146',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '供应链管理',
    controlName: '供应链管理',
    requirement: 'a）应确保供应商的选择符合国家有关规定；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'cloud',
    isHighRisk: 0,
    sortOrder: 146,
  },
  {
    id: 'gb22239-l2-security_construction-147',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '供应链管理',
    controlName: '供应链管理',
    requirement: 'b）应将供应链安全事件信息或安全威胁信息及时传达到云服务客户。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'cloud',
    isHighRisk: 0,
    sortOrder: 147,
  },
  {
    id: 'gb22239-l2-security_construction-148',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '移动应用软件采购',
    controlName: '移动应用软件采购',
    requirement: 'a）应保证移动终端安装、运行的应用软件来自可靠分发渠道或使用可靠证书签名；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'mobile',
    isHighRisk: 0,
    sortOrder: 148,
  },
  {
    id: 'gb22239-l2-security_construction-149',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '移动应用软件采购',
    controlName: '移动应用软件采购',
    requirement: 'b）应保证移动终端安装、运行的应用软件由可靠的开发者开发。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'mobile',
    isHighRisk: 0,
    sortOrder: 149,
  },
  {
    id: 'gb22239-l2-security_construction-150',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '移动应用软件开发',
    controlName: '移动应用软件开发',
    requirement: 'a）应对移动业务应用软件开发者进行资格审查；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'mobile',
    isHighRisk: 0,
    sortOrder: 150,
  },
  {
    id: 'gb22239-l2-security_construction-151',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '移动应用软件开发',
    controlName: '移动应用软件开发',
    requirement: 'b）应保证开发移动业务应用软件的签名证书合法性。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'mobile',
    isHighRisk: 0,
    sortOrder: 151,
  },
  {
    id: 'gb22239-l2-security_construction-152',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '产品采购和使用',
    controlName: '产品采购和使用',
    requirement: 'a）工业控制系统重要设备应通过专业机构的安全性检测后方可采购使用。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'industrial',
    isHighRisk: 0,
    sortOrder: 152,
  },
  {
    id: 'gb22239-l2-security_construction-153',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '外包软件开发',
    controlName: '外包软件开发',
    requirement: 'a）应在外包开发合同中规定针对开发单位、供应商的约束条款，包括设备及系统在生命周期内有关保密、禁止关键技术扩散和设备行业专用等方面的内容。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'industrial',
    isHighRisk: 0,
    sortOrder: 153,
  },
  {
    id: 'gb22239-l2-security_construction-154',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '大数据平台',
    controlName: '大数据平台',
    requirement: 'a）应选择安全合规的大数据平台，其所提供的大数据平台服务应为其所承载的大数据应用提供相应等级的安全保护能力；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'bigdata',
    isHighRisk: 0,
    sortOrder: 154,
  },
  {
    id: 'gb22239-l2-security_construction-155',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_construction',
    controlPoint: '大数据平台',
    controlName: '大数据平台',
    requirement: 'b）应以书面方式约定大数据平台提供者的权限与责任、各项服务内容和具体技术指标等，尤其是安全服务内容。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'bigdata',
    isHighRisk: 0,
    sortOrder: 155,
  },
  {
    id: 'gb22239-l2-security_maintenance-156',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '环境管理',
    controlName: '环境管理',
    requirement: 'a）应指定专门的部门或人员负责机房安全，对机房出入进行管理，定期对机房供配电、空调、温湿度控制、消防等设施进行维护管理；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 156,
  },
  {
    id: 'gb22239-l2-security_maintenance-157',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '环境管理',
    controlName: '环境管理',
    requirement: 'b）应对机房的安全管理做出规定，包括物理访问、物品进出和环境安全等；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 157,
  },
  {
    id: 'gb22239-l2-security_maintenance-158',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '环境管理',
    controlName: '环境管理',
    requirement: 'c）应不在重要区域接待来访人员，不随意放置含有敏感信息的纸档文件和移动介质等。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 158,
  },
  {
    id: 'gb22239-l2-security_maintenance-159',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '资产管理',
    controlName: '资产管理',
    requirement: 'a）应编制并保存与保护对象相关的资产清单，包括资产责任部门、重要程度和所处位置等内容。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 159,
  },
  {
    id: 'gb22239-l2-security_maintenance-160',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '介质管理',
    controlName: '介质管理',
    requirement: 'a）应将介质存放在安全的环境中，对各类介质进行控制和保护，实行存储环境专人管理，并根据存档介质的目录清单定期盘点；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 160,
  },
  {
    id: 'gb22239-l2-security_maintenance-161',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '介质管理',
    controlName: '介质管理',
    requirement: 'b）应对介质在物理传输过程中的人员选择、打包、交付等情况进行控制，并对介质的归档和查询等进行登记记录。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 161,
  },
  {
    id: 'gb22239-l2-security_maintenance-162',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '设备维护管理',
    controlName: '设备维护管理',
    requirement: 'a）应对各种设备（包括备份和冗余设备）、线路等指定专门的部门或人员定期进行维护管理；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 162,
  },
  {
    id: 'gb22239-l2-security_maintenance-163',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '设备维护管理',
    controlName: '设备维护管理',
    requirement: 'b）应对配套设施、软硬件维护管理做出规定，包括明确维护人员的责任、维修和服务的审批、维修过程的监督控制等。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 163,
  },
  {
    id: 'gb22239-l2-security_maintenance-164',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '漏洞和风险管理',
    controlName: '漏洞和风险管理',
    requirement: 'a）应采取必要的措施识别安全漏洞和隐患，对发现的安全漏洞和隐患及时进行修补或评估可能的影响后进行修补。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 164,
  },
  {
    id: 'gb22239-l2-security_maintenance-165',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '网络和系统安全管理',
    controlName: '网络和系统安全管理',
    requirement: 'a）应划分不同的管理员角色进行网络和系统的运维管理，明确各个角色的责任和权限；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 165,
  },
  {
    id: 'gb22239-l2-security_maintenance-166',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '网络和系统安全管理',
    controlName: '网络和系统安全管理',
    requirement: 'b）应指定专门的部门或人员进行账户管理，对申请账户、建立账户、删除账户等进行控制；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 166,
  },
  {
    id: 'gb22239-l2-security_maintenance-167',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '网络和系统安全管理',
    controlName: '网络和系统安全管理',
    requirement: 'c）应建立网络和系统安全管理制度，对安全策略、账户管理、配置管理、日志管理、日常操作、升级与打补丁、口令更新周期等方面作出规定；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 167,
  },
  {
    id: 'gb22239-l2-security_maintenance-168',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '网络和系统安全管理',
    controlName: '网络和系统安全管理',
    requirement: 'd）应制定重要设备的配置和操作手册，依据手册对设备进行安全配置和优化配置等；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 168,
  },
  {
    id: 'gb22239-l2-security_maintenance-169',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '网络和系统安全管理',
    controlName: '网络和系统安全管理',
    requirement: 'e）应详细记录运维操作日志，包括日常巡检工作、运行维护记录、参数的设置和修改等内容。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 169,
  },
  {
    id: 'gb22239-l2-security_maintenance-170',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '恶意代码防范管理',
    controlName: '恶意代码防范管理',
    requirement: 'a）应提高所有用户的防恶意代码意识，对外来计算机或存储设备接入系统前进行恶意代码检查等；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 170,
  },
  {
    id: 'gb22239-l2-security_maintenance-171',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '恶意代码防范管理',
    controlName: '恶意代码防范管理',
    requirement: 'b）应对恶意代码防范要求做出规定，包括防恶意代码软件的授权使用、恶意代码库升级、恶意代码的定期查杀等；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 171,
  },
  {
    id: 'gb22239-l2-security_maintenance-172',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '恶意代码防范管理',
    controlName: '恶意代码防范管理',
    requirement: 'c）应定期检查恶意代码库的升级情况，对截获的恶意代码进行及时分析处理。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 172,
  },
  {
    id: 'gb22239-l2-security_maintenance-173',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '配置管理',
    controlName: '配置管理',
    requirement: 'a）应记录和保存基本配置信息，包括网络拓扑结构、各个设备安装的软件组件、软件组件的版本和补丁信息、各个设备或软件组件的配置参数等。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 173,
  },
  {
    id: 'gb22239-l2-security_maintenance-174',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '密码管理',
    controlName: '密码管理',
    requirement: 'a）应遵循密码相关国家标准和行业标准；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 174,
  },
  {
    id: 'gb22239-l2-security_maintenance-175',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '密码管理',
    controlName: '密码管理',
    requirement: 'b）应使用国家密码管理主管部门认证核准的密码技术和产品。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 175,
  },
  {
    id: 'gb22239-l2-security_maintenance-176',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '变更管理',
    controlName: '变更管理',
    requirement: 'a）应明确变更需求，变更前根据变更需求制定变更方案，变更方案经过评审、审批后方可实施。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 176,
  },
  {
    id: 'gb22239-l2-security_maintenance-177',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '备份与恢复管理',
    controlName: '备份与恢复管理',
    requirement: 'a）应识别需要定期备份的重要业务信息、系统数据及软件系统等；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 177,
  },
  {
    id: 'gb22239-l2-security_maintenance-178',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '备份与恢复管理',
    controlName: '备份与恢复管理',
    requirement: 'b）应规定备份信息的备份方式、备份频度、存储介质、保存期等；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 178,
  },
  {
    id: 'gb22239-l2-security_maintenance-179',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '备份与恢复管理',
    controlName: '备份与恢复管理',
    requirement: 'c）应根据数据的重要性和数据对系统运行的影响，制定数据的备份策略和恢复策略、备份程序和恢复程序等。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 179,
  },
  {
    id: 'gb22239-l2-security_maintenance-180',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '安全事件处置',
    controlName: '安全事件处置',
    requirement: 'a）应及时向安全管理部门报告所发现的安全弱点和可疑事件；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 180,
  },
  {
    id: 'gb22239-l2-security_maintenance-181',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '安全事件处置',
    controlName: '安全事件处置',
    requirement: 'b）应制定安全事件报告和处置管理制度，明确不同安全事件的报告、处置和响应流程，规定安全事件的现场处理、事件报告和后期恢复的管理职责等；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 181,
  },
  {
    id: 'gb22239-l2-security_maintenance-182',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '安全事件处置',
    controlName: '安全事件处置',
    requirement: 'c）应在安全事件报告和响应处理过程中，分析和鉴定事件产生的原因，收集证据，记录处理过程，总结经验教训。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 182,
  },
  {
    id: 'gb22239-l2-security_maintenance-183',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '应急预案管理',
    controlName: '应急预案管理',
    requirement: 'a）应制定重要事件的应急预案，包括应急处理流程、系统恢复流程等内容；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 183,
  },
  {
    id: 'gb22239-l2-security_maintenance-184',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '应急预案管理',
    controlName: '应急预案管理',
    requirement: 'b）应定期对系统相关的人员进行应急预案培训，并进行应急预案的演练。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 184,
  },
  {
    id: 'gb22239-l2-security_maintenance-185',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '外包运维管理',
    controlName: '外包运维管理',
    requirement: 'a）应确保外包运维服务商的选择符合国家的有关规定；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 185,
  },
  {
    id: 'gb22239-l2-security_maintenance-186',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '外包运维管理',
    controlName: '外包运维管理',
    requirement: 'b）应与选定的外包运维服务商签订相关的协议，明确约定外包运维的范围、工作内容。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'general',
    isHighRisk: 0,
    sortOrder: 186,
  },
  {
    id: 'gb22239-l2-security_maintenance-187',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '云计算环境管理',
    controlName: '云计算环境管理',
    requirement: 'a）云计算平台的运维地点应位于中国境内，境外对境内云计算平台实施运维操作应遵循国家相关规定。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'cloud',
    isHighRisk: 0,
    sortOrder: 187,
  },
  {
    id: 'gb22239-l2-security_maintenance-188',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '感知节点管理',
    controlName: '感知节点管理',
    requirement: 'a）应指定人员定期巡视感知节点设备、网关节点设备的部署环境，对可能影响感知节点设备、网关节点设备正常工作的环境异常进行记录和维护；',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'iot',
    isHighRisk: 0,
    sortOrder: 188,
  },
  {
    id: 'gb22239-l2-security_maintenance-189',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '感知节点管理',
    controlName: '感知节点管理',
    requirement: 'b）应对感知节点设备、网关节点设备入库、存储、部署、携带、维修、丢失和报废等过程作出明确规定，并进行全程管理。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'iot',
    isHighRisk: 0,
    sortOrder: 189,
  },
  {
    id: 'gb22239-l2-security_maintenance-190',
    standardId: 'gb-t-22239-2019-l2',
    domain: 'security_maintenance',
    controlPoint: '大数据平台',
    controlName: '大数据平台',
    requirement: 'a）应建立数字资产安全管理策略，对数据全生命周期的操作规范、保护措施、管理人员职责等进行规定，包括并不限于数据采集、存储、处理、应用、流动、销毁等过程。',
    minLevel: 2,
    maxLevel: 2,
    extensionType: 'bigdata',
    isHighRisk: 0,
    sortOrder: 190,
  },
];

export const STANDARD_GB_T_22239_2019_L2 = {
  id: 'gb-t-22239-2019-l2',
  name: '信息安全技术 网络安全等级保护基本要求（二级）',
  code: 'GB/T 22239-2019-L2',
  version: '2019',
  description: '网络安全等级保护基本要求标准（二级），对应S2A2G2测评模板',
  grade: 2,
  domainCount: 10,
  itemCount: 190,
  isDefault: 0,
};

export function getStandardSeedL2() {
  return {
    standard: STANDARD_GB_T_22239_2019_L2,
    items: STANDARD_GB_T_22239_2019_L2_ITEMS,
  };
}
